### ISSUE TITLE
Memory usage for 7M model with 2^20 context too high

### ISSUE THREAD

**Issue by nongiga** [state-spaces/mamba#112]
Hi there,

I am attempting to pretrain a model on human DNA similar to the one in your paper. I am using a RTX A6000 with 50GB and using a batch size of 1. However, I am getting an CUDA Out of Memory Error. The largest model I manage to get a 2^20 context length on is the 700K one (D=96 and 10 layers). I also managed to train it on D=256 and 2 layers (same model dimensions but ~10th of the # of layers as the 7M model).

Given your largest model had 7M parameters and was trained on a A100-8GB GPU in batch sizes of 2, this is a ~10 times larger memory size than I expected.

- Should I expect to be able to run a 1.4M/7M model with 2^20 length and batch size of 1 on a single GPU? 
- Or did you use some level of model parallelism to make this work?

Sample traceback though depending on the model size the memory error shows up at a different step:

```Traceback (most recent call last):
  File "/code/dnalm/hyena-dna/train.py", line 695, in main
    trainer=train(config)
            ^^^^^^^^^^^^^
  File "/code/dnalm/hyena-dna/train.py", line 674, in train
    trainer.fit(model)
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 603, in fit
    call._call_and_handle_interrupt(
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 90, in launch
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 645, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1098, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1177, in _run_stage
    self._run_train()
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1200, in _run_train
    self.fit_loop.run()
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 214, in advance
    batch_output = self.batch_loop.run(kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 200, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 247, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 357, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1342, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/core/module.py", line 1661, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/core/optimizer.py", line 169, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/strategies/ddp.py", line 281, in optimizer_step
    optimizer_output = super().optimizer_step(optimizer, opt_idx, closure, model, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/strategies/strategy.py", line 234, in optimizer_step
    return self.precision_plugin.optimizer_step(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 121, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/torch/optim/optimizer.py", line 373, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/torch/optim/adamw.py", line 161, in step
    loss = closure()
           ^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 107, in _wrap_closure
    closure_result = closure()
                     ^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 147, in __call__
    self._result = self.closure(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 133, in closure
    step_output = self._step_fn()
                  ^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 406, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1480, in _call_strategy_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/strategies/ddp.py", line 352, in training_step
    return self.model(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/pytorch_lightning/overrides/base.py", line 98, in forward
    output = self._forward_module.training_step(*inputs, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/dnalm/hyena-dna/train.py", line 391, in training_step
    loss = self._shared_step(batch, batch_idx, prefix="train")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/dnalm/hyena-dna/train.py", line 324, in _shared_step
    x, y, w = self.forward(batch)
              ^^^^^^^^^^^^^^^^^^^
  File "/code/dnalm/hyena-dna/train.py", line 309, in forward
    return self.task.forward(batch, self.encoder, self.model, self.decoder, self._state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/dnalm/hyena-dna/src/tasks/tasks.py", line 173, in forward
    x, state = model(x, **w, state=_state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/dnalm/hyena-dna/src/models/sequence/mamba.py", line 288, in forward
    hidden_states=super(MambaLMHeadModel,self).forward(input_ids, position_ids=position_ids,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/mamba_ssm/models/mixer_seq_simple.py", line 233, in forward
    hidden_states = self.backbone(input_ids, inference_params=inference_params)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/mamba_ssm/models/mixer_seq_simple.py", line 155, in forward
    hidden_states, residual = layer(
                              ^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/mamba_ssm/modules/mamba_simple.py", line 349, in forward
    hidden_states = self.mixer(hidden_states, inference_params=inference_params)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mambaforge/envs/mamba-dna2/lib/python3.11/site-packages/mamba_ssm/modules/mamba_simple.py", line 136, in forward
    self.in_proj.weight @ rearrange(hidden_states, "b l d -> d (b l)"),
    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 5.00 GiB. GPU 0 has a total capacty of 47.54 GiB of which 493.75 MiB is free. Including non-PyTorch memory, this process has 47.05 GiB memory in use. Of the allocated memory 37.40 GiB is allocated by PyTorch, and 8.42 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF```

**Comment by albertfgu** [comment]
- Where did the paper specify the batch size 2? It should have been 1 (global batch size 2^20)
- We actually used a 40Gb GPU for these experiments
- I think one big difference is that we used gradient checkpointing per block
- I believe the small size (1.4M) fit without checkpointing in a 40Gb GPU. Seems like it might be ballpark correct (within 2x of what you're seeing)

**Comment by nongiga** [comment]
Sounds cool, could you give any hints as to how you implemented gradient checkpointing per block?

**Comment by albertfgu** [comment]
I think the options exist in the HyenaDNA codebase

**Comment by nongiga** [comment]
Amazing, thanks!

**Comment by damiano-sg** [comment]
Hi @nongiga any news about the gradient checkpointing? Were you able to implement it? I'm trying to do the same but the HyenaDNA codebase is quite different.

**Comment by Dongzhikang** [comment]
> I think the options exist in the HyenaDNA codebase

I tried the similar approach in HyenaDNA codebase by using

```
class CheckpointedModule(torch.nn.Module):
    def __init__(self, layer):
        super().__init__()
        self.layer = layer
    def forward(self, x, inference_params):
        return checkpoint(self.layer, x, inference_params, use_reentrant=False)
def create_block(
    d_model,
    ssm_cfg=None,
    norm_epsilon=1e-5,
    rms_norm=False,
    residual_in_fp32=False,
    fused_add_norm=False,
    layer_idx=None,
    device=None,
    dtype=None,
):
    if ssm_cfg is None:
        ssm_cfg = {}
    factory_kwargs = {"device": device, "dtype": dtype}
    mixer_cls = partial(Mamba, layer_idx=layer_idx, **ssm_cfg, **factory_kwargs)
    norm_cls = partial(
        nn.LayerNorm if not rms_norm else RMSNorm, eps=norm_epsilon, **factory_kwargs
    )
    block = Block(
        d_model,
        mixer_cls,
        norm_cls=norm_cls,
        fused_add_norm=fused_add_norm,
        residual_in_fp32=residual_in_fp32,
    )
    block.mixer = CheckpointedModule(block.mixer)
    block.layer_idx = layer_idx
    return block
```

But I got the following error:
```
  File "/mamba_ssm/ops/selective_scan_interface.py",
    conv1d_out, delta, A, B, C, D, delta_bias, scan_intermediates, out) = ctx.saved_tensors
RuntimeError: !grad_accumulator_.expired() INTERNAL ASSERT FAILED at "../torch/csrc/autograd/saved_variable.cpp":226, please report a bug to PyTorch. No grad accumulator for a saved leaf
```

Could you please share how did you do gradient checkpointing?
