### ISSUE TITLE
AssertionError when training mamba model on my own dataset

### ISSUE THREAD

**Issue by xianyu0623** [state-spaces/mamba#134]
Hi there! I want to train a mamba language model from scratch on my own dataset. However, during the training of process, there is a problem. When I set CUDA_LAUNCH_BLOCKING=1 and debug, I have log like this:
```
(base) xxx@n1:~/yx/msa_project$ CUDA_LAUNCH_BLOCKING=1 python train.py > debug.txt
Epoch 1:   0%|                                                                                   | 1898/56927313 [01:09<339:47:16, 46.54batch/s, loss=3.94]../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [2,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [2,0,0], thread: [110,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [2,0,0], thread: [125,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [2,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [4,0,0], thread: [97,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [4,0,0], thread: [66,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [4,0,0], thread: [67,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [4,0,0], thread: [81,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [4,0,0], thread: [82,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [4,0,0], thread: [34,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [4,0,0], thread: [36,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [4,0,0], thread: [37,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [4,0,0], thread: [49,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [4,0,0], thread: [51,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [4,0,0], thread: [52,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [4,0,0], thread: [4,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [4,0,0], thread: [6,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [4,0,0], thread: [7,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [4,0,0], thread: [19,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [4,0,0], thread: [21,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [4,0,0], thread: [22,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [72,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [74,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [75,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [87,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [89,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [90,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [102,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [104,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [105,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [117,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [119,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [120,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [42,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [44,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [45,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [57,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [59,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [60,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [12,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [14,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [15,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [27,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [29,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [3,0,0], thread: [30,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Epoch 1:   0%|                                                                                   | 1901/56927313 [01:09<581:27:51, 27.19batch/s, loss=3.94]
Traceback (most recent call last):
  File "train.py", line 44, in <module>
    output = model(x)
  File "/home/xxx/.conda/envs/yx_msa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/yx/msa_project/model.py", line 234, in forward
    hidden_states = self.backbone(input_ids, inference_params=inference_params)
  File "/home/xxx/.conda/envs/yx_msa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/yx/msa_project/model.py", line 153, in forward
    hidden_states = self.embedding(input_ids)
  File "/home/xxx/.conda/envs/yx_msa/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/.conda/envs/yx_msa/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/home/xxx/.conda/envs/yx_msa/lib/python3.8/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```
Here is my code:
``` python
from data_utils import ProteinTokenizer
from data_utils import ProteinSeqs
from dataclasses import dataclass, field
import torch.optim as optim
from model import MambaLMHeadModel
from tqdm import tqdm
batch_size = 64
epoch = 1
learning_rate = 1e-8
device = torch.device("cuda")
class MambaConfig:
    d_model: int = 1
    n_layer: int = 6
    vocab_size: int = 51
    ssm_cfg: dict = {}
    rms_norm: bool = True
    residual_in_fp32: bool = True
    fused_add_norm: bool = True
    # pad_vocab_size_multiple: int = 8
config = MambaConfig()
traindataset = ProteinSeqs('/home/xxx/yx/msa_project/seqs.txt', max_length = 15 )
trainloader = torch.utils.data.DataLoader(traindataset, batch_size = batch_size, shuffle = False, num_workers = 4, drop_last = True)
model = MambaLMHeadModel(config=config)
# model = torch.nn.DataParallel(model)
model.to(device)
optimizer = optim.Adam(model.parameters(), lr=learning_rate)
criterion = nn.CrossEntropyLoss()
model.train()

for epoch_idx in range(epoch):
    total_loss = 0
    with tqdm(trainloader, unit="batch") as tepoch: 
        for x, y in tepoch:
            tepoch.set_description(f"Epoch {epoch_idx+1}")
            x = x.long().to(device)
            y = y.to(device)
            # print(y.shape)

            output = model(x)
            # print(output.shape)
            # print(output.shape)

            loss = criterion(output, y)
        
            try:
                total_loss += loss.item()
            except:
                print(x)
                print(y)
                print(output.shape)
                print(y.shape)
                
                exit()

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            tepoch.set_postfix(loss=loss.item())


    avg_loss = total_loss / len(trainloader)
    print(f"Average Loss for Epoch {epoch_idx+1} : {avg_loss}")
model.save_pretrained('/home/xxx/yx/msa_project/model')
``` python
The dataset function
``` python
def vectorization(sentence, next_char, maxlen):
    chars = "*-$#ACDEFGHIKLMNPQRSTVWYacdefghiklmnpqrstvwyBZJXbzjx"
    #here * is taken as [cls], $ is taken as [start], # is taken as [end]
    char_indices = dict((c, i) for i, c in enumerate(chars))
    # x = np.zeros((len(chars), maxlen))
    x = np.zeros((maxlen + 1))
    y = np.zeros((len(chars) - 1))
    x[0] = char_indices['*']
    for t, char in enumerate(sentence):
        if char not in chars:
            char = 'X'
        x[t + 1] = char_indices[char]
        # print(f"x[{t}] = {x[t]}, the char is {char}")
    if next_char not in chars:
        next_char = 'X'
    y[char_indices[next_char] - 1] = 1
    return x, y
class ProteinSeqs(Dataset):
    def __init__(self, file_path, max_length = 1024):
        #read file with only 1 line
        with open(file_path, 'r') as f:
            self.seqs = f.readline()
        self.max_length = max_length
        
    def __len__(self):
        return len(self.seqs) - self.max_length
    def __getitem__(self, idx):
        next_char = self.seqs[idx + self.max_length]
        sentence = self.seqs[idx: idx + self.max_length]
        sentence, next_char = vectorization(sentence, next_char, self.max_length)
        return torch.from_numpy(sentence), next_char
    
``` python

**Comment by albertfgu** [comment]
Check that the model's embedding dim is large enough for your vocab?

**Comment by coding-sharks** [comment]
Hello！I am working in mamba，maybe we can add the WeChat to communicate with each other, my wechat is: ABC4848674264

**Comment by duan-song** [comment]
Hello, I have the same problem, have you solved it?

**Comment by chrisyu2002** [comment]
Hello, I have the same problem, have you solved it?
