### ISSUE TITLE
TypeError: decode() got an unexpected keyword argument 'min_p'

### ISSUE THREAD

**Issue by Seefreem** [state-spaces/mamba#147]
Hi, I am running this repo, but I get the following error. Does anyone know how to fix this? And what is the meaning of 'min_p'? Thanks!:

(base) seelur@seelur-B560M-HDV-A-R2-0:~/git/mamba$ python benchmarks/benchmark_generation_mamba_simple.py --model-name "state-spaces/mamba-790m" --prompt "My cat wrote all this CUDA code for a new language model and" --topp 0.9 --temperature 0.7 --repetition-penalty 1.2
Loading model state-spaces/mamba-790m
Number of parameters: 793204224
Traceback (most recent call last):
  File "/home/seelur/git/mamba/benchmarks/benchmark_generation_mamba_simple.py", line 85, in <module>
    out = fn()
          ^^^^
  File "/home/seelur/git/mamba/benchmarks/benchmark_generation_mamba_simple.py", line 59, in <lambda>
    fn = lambda: model.generate(
                 ^^^^^^^^^^^^^^^
  File "/home/seelur/anaconda3/lib/python3.11/site-packages/mamba_ssm/utils/generation.py", line 244, in generate
    output = decode(
             ^^^^^^^
  File "/home/seelur/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: decode() got an unexpected keyword argument 'min_p'

My environment:
nvcc V12.2.140
torch 2.1.0
Transformers 4.32.1

**Comment by Eupham** [comment]
I'm getting the same problem.  I went straight from pip install mamba-ssm and in generate I've added min_p as an argument.  I'm getting the same error.  This was in a brand new colab env.

**Comment by Eupham** [comment]
It works now.  Thanks for the fix.
