### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by ICharlotteI** [state-spaces/mamba#186]
Installing causal_conv1d and mamba on a linux server system shows a cuda version below 11.6, when in fact the native cuda version is 11.7. The cuda version of pytorch also runs with 11.7 and works fine, so the cuda version should be fine. How to fix it.

**Comment by MuyuenHoshino** [comment]
> Installing causal_conv1d and mamba on a linux server system shows a cuda version below 11.6, when in fact the native cuda version is 11.7. The cuda version of pytorch also runs with 11.7 and works fine, so the cuda version should be fine. How to fix it.

It may depend on the nvcc version but not the nvidia driver. But I have not intsalled it successfully now.

**Comment by ICharlotteI** [comment]
> > Installing causal_conv1d and mamba on a linux server system shows a cuda version below 11.6, when in fact the native cuda version is 11.7. The cuda version of pytorch also runs with 11.7 and works fine, so the cuda version should be fine. How to fix it.
> 
> It may depend on the nvcc version but not the nvidia driver. But I have not intsalled it successfully now.

Yes, I also found that the version of nvcc needs to be greater than 11.6. I have successfully installed it. The current approach is to clone the causal_conv1d and mamba libraries locally, then modify the code limiting the nvcc version in the setup file, and finally install it using the command "pip install .". I don't know if there will be other bugs after this, but it can be used normally for now.

**Comment by ICharlotteI** [comment]
> > > > > Installing causal_conv1d and mamba on a linux server system shows a cuda version below 11.6, when in fact the native cuda version is 11.7. The cuda version of pytorch also runs with 11.7 and works fine, so the cuda version should be fine. How to fix it.
> > > > 
> > > > 
> > > > It may depend on the nvcc version but not the nvidia driver. But I have not intsalled it successfully now.
> > > 
> > > 
> > > Yes, I also found that the version of nvcc needs to be greater than 11.6. I have successfully installed it. The current approach is to clone the causal_conv1d and mamba libraries locally, then modify the code limiting the nvcc version in the setup file, and finally install it using the command "pip install .". I don't know if there will be other bugs after this, but it can be used normally for now.
> > 
> > 
> > Thanks a lot. I have also installed it successfully.
> 
> Hello, I have encountered some installation problems and some files are missing. Have you compiled successfully? Can you lend me these files? The files and their addresses are
> 
> 1. /mamba/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/selective_scan_bwd_bf16_complex.o
> 2. /mamba/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/selective_scan_bwd_bf16_real.o
> 3. /mamba/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/selective_scan_bwd_fp16_complex.o
> 4. /mamba/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/selective_scan_bwd_fp16_real.o
> 5. /mamba/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/selective_scan_bwd_fp32_complex.o
> 6. /mamba/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/selective_scan_bwd_fp32_real.o

Sorry, I used Python 3.9 when installing and compiling.

**Comment by perfectFeng** [comment]
> > > Installing causal_conv1d and mamba on a linux server system shows a cuda version below 11.6, when in fact the native cuda version is 11.7. The cuda version of pytorch also runs with 11.7 and works fine, so the cuda version should be fine. How to fix it.
> > 
> > 
> > It may depend on the nvcc version but not the nvidia driver. But I have not intsalled it successfully now.
> 
> Yes, I also found that the version of nvcc needs to be greater than 11.6. I have successfully installed it. The current approach is to clone the causal_conv1d and mamba libraries locally, then modify the code limiting the nvcc version in the setup file, and finally install it using the command "pip install .". I don't know if there will be other bugs after this, but it can be used normally for now.

My system is cuda11.2, but I successfully installed cuda11.8 in the conda, my conda environment  is：
1.nvcc -V:
  nvcc: NVIDIA (R) Cuda compiler driver
  Copyright (c) 2005-2022 NVIDIA Corporation
  Built on Wed_Sep_21_10:33:58_PDT_2022
  Cuda compilation tools, release 11.8, V11.8.89
  Build cuda_11.8.r11.8/compiler.31833905_0
2.python --version
  Python 3.10.13
3. torch.__version__
  '2.1.1+cu118'

however, the error message cuda>11.6 was still reported during the installation. I cloned mamba locally and commented the cuda version requirements, that is:
#if bare_metal_version < Version("11.6"):
#            raise RuntimeError(
#                f"{PACKAGE_NAME} is only supported on CUDA 11.6 and above.  "
#                "Note: make sure nvcc has a supported version by running nvcc -V."
#           )

But there is still a problem:
Traceback (most recent call last):
      File "~/.conda/envs/Mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
        subprocess.run(
      File "~/.conda/envs/Mamba/lib/python3.10/subprocess.py", line 526, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

Have you encountered similar problems, or can you share the environment in which you successfully installed it?

Thank you very much for your reply！

**Comment by perfectFeng** [comment]
> > > > > Installing causal_conv1d and mamba on a linux server system shows a cuda version below 11.6, when in fact the native cuda version is 11.7. The cuda version of pytorch also runs with 11.7 and works fine, so the cuda version should be fine. How to fix it.
> > > > 
> > > > 
> > > > It may depend on the nvcc version but not the nvidia driver. But I have not intsalled it successfully now.
> > > 
> > > 
> > > Yes, I also found that the version of nvcc needs to be greater than 11.6. I have successfully installed it. The current approach is to clone the causal_conv1d and mamba libraries locally, then modify the code limiting the nvcc version in the setup file, and finally install it using the command "pip install .". I don't know if there will be other bugs after this, but it can be used normally for now.
> > 
> > 
> > My system is cuda11.2, but I successfully installed cuda11.8 in the conda, my conda environment is： 1.nvcc -V: nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2022 NVIDIA Corporation Built on Wed_Sep_21_10:33:58_PDT_2022 Cuda compilation tools, release 11.8, V11.8.89 Build cuda_11.8.r11.8/compiler.31833905_0 2.python --version Python 3.10.13 3. torch.**version** '2.1.1+cu118'
> > however, the error message cuda>11.6 was still reported during the installation. I cloned mamba locally and commented the cuda version requirements, that is: if bare_metal_version < Version("11.6"): raise RuntimeError( f"{PACKAGE_NAME} is only supported on CUDA 11.6 and above. " "Note: make sure nvcc has a supported version by running nvcc -V." )
> > But there is still a problem: Traceback (most recent call last): File "/.conda/envs/Mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build subprocess.run( File "/.conda/envs/Mamba/lib/python3.10/subprocess.py", line 526, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> > Have you encountered similar problems, or can you share the environment in which you successfully installed it?
> > Thank you very much for your reply！
> 
> Even after I cloned mamba locally and changed the cuda version requirements, I still ran into version issues. Upon inspection, it is found that its dependent causal-conv1d still has cuda version requirements. So I cloned and installed causal-conv1d locally and then did the same for mamba. My environment is Python 3.9.17, cuda driver 11.7, and pytorch 1.13.1. And in my impression, other people have had problems with pytorch versions >= 2.0. I guess yours might be related to pytorch versions as well.


Thank you! I installed causal-conv1d successfully, all these problems only occur with mamba installation, I will try it again with low pytorch version！

**Comment by perfectFeng** [comment]
> > > > > Installing causal_conv1d and mamba on a linux server system shows a cuda version below 11.6, when in fact the native cuda version is 11.7. The cuda version of pytorch also runs with 11.7 and works fine, so the cuda version should be fine. How to fix it.
> > > > 
> > > > 
> > > > It may depend on the nvcc version but not the nvidia driver. But I have not intsalled it successfully now.
> > > 
> > > 
> > > Yes, I also found that the version of nvcc needs to be greater than 11.6. I have successfully installed it. The current approach is to clone the causal_conv1d and mamba libraries locally, then modify the code limiting the nvcc version in the setup file, and finally install it using the command "pip install .". I don't know if there will be other bugs after this, but it can be used normally for now.
> > 
> > 
> > My system is cuda11.2, but I successfully installed cuda11.8 in the conda, my conda environment is： 1.nvcc -V: nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2022 NVIDIA Corporation Built on Wed_Sep_21_10:33:58_PDT_2022 Cuda compilation tools, release 11.8, V11.8.89 Build cuda_11.8.r11.8/compiler.31833905_0 2.python --version Python 3.10.13 3. torch.**version** '2.1.1+cu118'
> > however, the error message cuda>11.6 was still reported during the installation. I cloned mamba locally and commented the cuda version requirements, that is: if bare_metal_version < Version("11.6"): raise RuntimeError( f"{PACKAGE_NAME} is only supported on CUDA 11.6 and above. " "Note: make sure nvcc has a supported version by running nvcc -V." )
> > But there is still a problem: Traceback (most recent call last): File "/.conda/envs/Mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build subprocess.run( File "/.conda/envs/Mamba/lib/python3.10/subprocess.py", line 526, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> > Have you encountered similar problems, or can you share the environment in which you successfully installed it?
> > Thank you very much for your reply！
> 
> Even after I cloned mamba locally and changed the cuda version requirements, I still ran into version issues. Upon inspection, it is found that its dependent causal-conv1d still has cuda version requirements. So I cloned and installed causal-conv1d locally and then did the same for mamba. My environment is Python 3.9.17, cuda driver 11.7, and pytorch 1.13.1. And in my impression, other people have had problems with pytorch versions >= 2.0. I guess yours might be related to pytorch versions as well.

I tried it according to the version information you provided. Unfortunately, I still got the same error and could not compile some files. Can you share with me the successfully compiled files? I would like to try again. The files that were not successfully compiled are as follows:
/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_bf16_complex.o
/mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_bf16_real.o
/mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_fp16_complex.o
/mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_fp16_real.o
/mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_fp32_complex.o
/mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_fp32_real.o

**Comment by MuyuenHoshino** [comment]
> I tried it according to the version information you provided. Unfortunately, I still got the same error and could not compile some files. Can you share with me the successfully compiled files? I would like to try again. The files that were not successfully compiled are as follows:

Maybe you can use the .whl file of mamba in the releases directly. If you are trapped in building causal-conv1d, just get the whl of it from the guessing url and pip install it first. It is recommended to add "--verbose" when using pip install

**Comment by perfectFeng** [comment]
> > I tried it according to the version information you provided. Unfortunately, I still got the same error and could not compile some files. Can you share with me the successfully compiled files? I would like to try again. The files that were not successfully compiled are as follows:
> 
> Maybe you can use the .whl file of mamba in the releases directly. If you are trapped in building causal-conv1d, just get the whl of it from the guessing url and pip install it first. It is recommended to add "--verbose" when using pip install

I have tried installing from pip, but it will report an error  as follows, as my system cuda is 11.2. 

RuntimeError: mamba_ssm is only supported on CUDA 11.6 and above.  Note: make sure nvcc has a supported version by running nvcc -V.

Although the cuda version installed in conda is greater than 11.6, the pip installation will automatically detect the version in /usr/local/cuda which I cannot modify.

So I want to install from the source code as i can modify the cuda version limitation manually.

**Comment by MuyuenHoshino** [comment]
> > > I tried it according to the version information you provided. Unfortunately, I still got the same error and could not compile some files. Can you share with me the successfully compiled files? I would like to try again. The files that were not successfully compiled are as follows:
> > 
> > 
> > Maybe you can use the .whl file of mamba in the releases directly. If you are trapped in building causal-conv1d, just get the whl of it from the guessing url and pip install it first. It is recommended to add "--verbose" when using pip install
> 
> I have tried installing from pip, but it will report an error as follows, as my system cuda is 11.2.
> 
> RuntimeError: mamba_ssm is only supported on CUDA 11.6 and above. Note: make sure nvcc has a supported version by running nvcc -V.
> 
> Although the cuda version installed in conda is greater than 11.6, the pip installation will automatically detect the version in /usr/local/cuda which I cannot modify.
> 
> So I want to install from the source code as i can modify the cuda version limitation manually.

My cuda version is 11.5, and I also install a higher version in conda(12.1.1). But I succeeded using the method. It's so weird.

**Comment by everglow1024** [comment]
> > > > > > Installing causal_conv1d and mamba on a linux server system shows a cuda version below 11.6, when in fact the native cuda version is 11.7. The cuda version of pytorch also runs with 11.7 and works fine, so the cuda version should be fine. How to fix it.
> > > > > 
> > > > > 
> > > > > It may depend on the nvcc version but not the nvidia driver. But I have not intsalled it successfully now.
> > > > 
> > > > 
> > > > Yes, I also found that the version of nvcc needs to be greater than 11.6. I have successfully installed it. The current approach is to clone the causal_conv1d and mamba libraries locally, then modify the code limiting the nvcc version in the setup file, and finally install it using the command "pip install .". I don't know if there will be other bugs after this, but it can be used normally for now.
> > > 
> > > 
> > > My system is cuda11.2, but I successfully installed cuda11.8 in the conda, my conda environment is： 1.nvcc -V: nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2022 NVIDIA Corporation Built on Wed_Sep_21_10:33:58_PDT_2022 Cuda compilation tools, release 11.8, V11.8.89 Build cuda_11.8.r11.8/compiler.31833905_0 2.python --version Python 3.10.13 3. torch.**version** '2.1.1+cu118'
> > > however, the error message cuda>11.6 was still reported during the installation. I cloned mamba locally and commented the cuda version requirements, that is: if bare_metal_version < Version("11.6"): raise RuntimeError( f"{PACKAGE_NAME} is only supported on CUDA 11.6 and above. " "Note: make sure nvcc has a supported version by running nvcc -V." )
> > > But there is still a problem: Traceback (most recent call last): File "/.conda/envs/Mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build subprocess.run( File "/.conda/envs/Mamba/lib/python3.10/subprocess.py", line 526, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> > > Have you encountered similar problems, or can you share the environment in which you successfully installed it?
> > > Thank you very much for your reply！
> > 
> > 
> > Even after I cloned mamba locally and changed the cuda version requirements, I still ran into version issues. Upon inspection, it is found that its dependent causal-conv1d still has cuda version requirements. So I cloned and installed causal-conv1d locally and then did the same for mamba. My environment is Python 3.9.17, cuda driver 11.7, and pytorch 1.13.1. And in my impression, other people have had problems with pytorch versions >= 2.0. I guess yours might be related to pytorch versions as well.
> 
> I tried it according to the version information you provided. Unfortunately, I still got the same error and could not compile some files. Can you share with me the successfully compiled files? I would like to try again. The files that were not successfully compiled are as follows: /mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_bf16_complex.o /mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_bf16_real.o /mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_fp16_complex.o /mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_fp16_real.o /mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_fp32_complex.o /mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_fp32_real.o

Hello, I have the same problems as you. Have you managed to resolve them yet?

**Comment by perfectFeng** [comment]
> > > > > > > Installing causal_conv1d and mamba on a linux server system shows a cuda version below 11.6, when in fact the native cuda version is 11.7. The cuda version of pytorch also runs with 11.7 and works fine, so the cuda version should be fine. How to fix it.
> > > > > > 
> > > > > > 
> > > > > > It may depend on the nvcc version but not the nvidia driver. But I have not intsalled it successfully now.
> > > > > 
> > > > > 
> > > > > Yes, I also found that the version of nvcc needs to be greater than 11.6. I have successfully installed it. The current approach is to clone the causal_conv1d and mamba libraries locally, then modify the code limiting the nvcc version in the setup file, and finally install it using the command "pip install .". I don't know if there will be other bugs after this, but it can be used normally for now.
> > > > 
> > > > 
> > > > My system is cuda11.2, but I successfully installed cuda11.8 in the conda, my conda environment is： 1.nvcc -V: nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2022 NVIDIA Corporation Built on Wed_Sep_21_10:33:58_PDT_2022 Cuda compilation tools, release 11.8, V11.8.89 Build cuda_11.8.r11.8/compiler.31833905_0 2.python --version Python 3.10.13 3. torch.**version** '2.1.1+cu118'
> > > > however, the error message cuda>11.6 was still reported during the installation. I cloned mamba locally and commented the cuda version requirements, that is: if bare_metal_version < Version("11.6"): raise RuntimeError( f"{PACKAGE_NAME} is only supported on CUDA 11.6 and above. " "Note: make sure nvcc has a supported version by running nvcc -V." )
> > > > But there is still a problem: Traceback (most recent call last): File "/.conda/envs/Mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build subprocess.run( File "/.conda/envs/Mamba/lib/python3.10/subprocess.py", line 526, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> > > > Have you encountered similar problems, or can you share the environment in which you successfully installed it?
> > > > Thank you very much for your reply！
> > > 
> > > 
> > > Even after I cloned mamba locally and changed the cuda version requirements, I still ran into version issues. Upon inspection, it is found that its dependent causal-conv1d still has cuda version requirements. So I cloned and installed causal-conv1d locally and then did the same for mamba. My environment is Python 3.9.17, cuda driver 11.7, and pytorch 1.13.1. And in my impression, other people have had problems with pytorch versions >= 2.0. I guess yours might be related to pytorch versions as well.
> > 
> > 
> > I tried it according to the version information you provided. Unfortunately, I still got the same error and could not compile some files. Can you share with me the successfully compiled files? I would like to try again. The files that were not successfully compiled are as follows: /mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_bf16_complex.o /mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_bf16_real.o /mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_fp16_complex.o /mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_fp16_real.o /mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_fp32_complex.o /mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_fp32_real.o
> 
> Hello, I have the same problems as you. Have you managed to resolve them yet?

not yet o(╥﹏╥)o

**Comment by perfectFeng** [comment]
> > > > > > > Installing causal_conv1d and mamba on a linux server system shows a cuda version below 11.6, when in fact the native cuda version is 11.7. The cuda version of pytorch also runs with 11.7 and works fine, so the cuda version should be fine. How to fix it.
> > > > > > 
> > > > > > 
> > > > > > It may depend on the nvcc version but not the nvidia driver. But I have not intsalled it successfully now.
> > > > > 
> > > > > 
> > > > > Yes, I also found that the version of nvcc needs to be greater than 11.6. I have successfully installed it. The current approach is to clone the causal_conv1d and mamba libraries locally, then modify the code limiting the nvcc version in the setup file, and finally install it using the command "pip install .". I don't know if there will be other bugs after this, but it can be used normally for now.
> > > > 
> > > > 
> > > > My system is cuda11.2, but I successfully installed cuda11.8 in the conda, my conda environment is： 1.nvcc -V: nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2022 NVIDIA Corporation Built on Wed_Sep_21_10:33:58_PDT_2022 Cuda compilation tools, release 11.8, V11.8.89 Build cuda_11.8.r11.8/compiler.31833905_0 2.python --version Python 3.10.13 3. torch.**version** '2.1.1+cu118'
> > > > however, the error message cuda>11.6 was still reported during the installation. I cloned mamba locally and commented the cuda version requirements, that is: if bare_metal_version < Version("11.6"): raise RuntimeError( f"{PACKAGE_NAME} is only supported on CUDA 11.6 and above. " "Note: make sure nvcc has a supported version by running nvcc -V." )
> > > > But there is still a problem: Traceback (most recent call last): File "/.conda/envs/Mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build subprocess.run( File "/.conda/envs/Mamba/lib/python3.10/subprocess.py", line 526, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> > > > Have you encountered similar problems, or can you share the environment in which you successfully installed it?
> > > > Thank you very much for your reply！
> > > 
> > > 
> > > Even after I cloned mamba locally and changed the cuda version requirements, I still ran into version issues. Upon inspection, it is found that its dependent causal-conv1d still has cuda version requirements. So I cloned and installed causal-conv1d locally and then did the same for mamba. My environment is Python 3.9.17, cuda driver 11.7, and pytorch 1.13.1. And in my impression, other people have had problems with pytorch versions >= 2.0. I guess yours might be related to pytorch versions as well.
> > 
> > 
> > I tried it according to the version information you provided. Unfortunately, I still got the same error and could not compile some files. Can you share with me the successfully compiled files? I would like to try again. The files that were not successfully compiled are as follows: /mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_bf16_complex.o /mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_bf16_real.o /mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_fp16_complex.o /mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_fp16_real.o /mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_fp32_complex.o /mamba/mamba/build/temp.linux-x86_64-cpython-39/csrc/selective_scan/selective_scan_bwd_fp32_real.o
> 
> Hello, I have the same problems as you. Have you managed to resolve them yet?

I installed mamba successfully! But the solution is to need someone else to provide the compiled files I mentioned above. The cuda version can be solved by modifying the setup.py file. For the problem of '['ninja', '-v'], you need to change the '-v' in the corresponding file to '--version', and then use the file compiled by others directly Recompile. Considering that it is a system file, I changed the '--version' back to '-v' after the compilation. In theory, the installation has been completed. I also encountered a problem with gcc when import it, it can be solved by modifying the path.

**Comment by gaopinghai** [comment]
> > > Installing causal_conv1d and mamba on a linux server system shows a cuda version below 11.6, when in fact the native cuda version is 11.7. The cuda version of pytorch also runs with 11.7 and works fine, so the cuda version should be fine. How to fix it.
> > 
> > 
> > It may depend on the nvcc version but not the nvidia driver. But I have not intsalled it successfully now.
> 
> Yes, I also found that the version of nvcc needs to be greater than 11.6. I have successfully installed it. The current approach is to clone the causal_conv1d and mamba libraries locally, then modify the code limiting the nvcc version in the setup file, and finally install it using the command "pip install .". I don't know if there will be other bugs after this, but it can be used normally for now.

I also wonder whether there will be any errors or not!

**Comment by xiaoxiaoli666** [comment]
> --verbose

Hello,where did you get the files? I met the same problem when install mamba,. I successfully install causal-conv1d,but can't install mamba, when it comes to Building wheel for mamba-ssm (setup.py) ... \,the process can't move on. Thank you very much.

**Comment by v-nhandt21** [comment]
I got the same problem, and I solve it by install in terminal screen

Nvcc in my VScode
![image](https://github.com/state-spaces/mamba/assets/36092323/d80f4c0b-1e27-459c-9f6c-de23225af2ad)

Nvcc in my terminal
![image](https://github.com/state-spaces/mamba/assets/36092323/f66c3f90-440e-4ef2-9ec0-c6a87f7bdf6c)

Therefore, make sure the bash session using for install mamba using cuda>11.6

PS: how to install cuda > 11.6 
- wget https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda_11.8.0_520.61.05_linux.run
- sudo sh cuda_11.8.0_520.61.05_linux.run

uncheck driver installer

export PATH=/usr/local/cuda-X.X/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-X.X/lib64:$LD_LIBRARY_PATH

source ~/.bashrc

**Comment by Pengfei-Hu** [comment]
> > > Installing causal_conv1d and mamba on a linux server system shows a cuda version below 11.6, when in fact the native cuda version is 11.7. The cuda version of pytorch also runs with 11.7 and works fine, so the cuda version should be fine. How to fix it.
> > 
> > 
> > It may depend on the nvcc version but not the nvidia driver. But I have not intsalled it successfully now.
> 
> Yes, I also found that the version of nvcc needs to be greater than 11.6. I have successfully installed it. The current approach is to clone the causal_conv1d and mamba libraries locally, then modify the code limiting the nvcc version in the setup file, and finally install it using the command "pip install .". I don't know if there will be other bugs after this, but it can be used normally for now.

Could you please provide more information of your env? I use cuda 11.7, torch 1.13 as well, and I successfully installed it. However, although I run the code of sing layer of Mamba successfully, someting seems wrong when I run multi layers of Mamba in Hugging Face. So do you try scripts of Mamba on Hugging Face?

**Comment by hiterjoshua** [comment]
Hi there, I had encountered with this problem, and I download the soure code to make analysis, it seems that the CUDA_home is not inconsistent with the library_path, so nvcc_V is cuda 11-7,while cuda_home is 11.2, when I make the corrections, this problem fixed.

**Comment by hiterjoshua** [comment]
> Installing causal_conv1d and mamba on a linux server system shows a cuda version below 11.6, when in fact the native cuda version is 11.7. The cuda version of pytorch also runs with 11.7 and works fine, so the cuda version should be fine. How to fix it.

export CUDA_HOME=/usr/local/cuda-11.7
export PATH=/usr/local/cuda-11.7/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-11.7/lib64:$LD_LIBRARY_PATH

**Comment by hiterjoshua** [comment]
> Hi there, I had encountered with this problem, and I download the soure code to make analysis, it seems that the CUDA_home is not inconsistent with the library_path, so nvcc_V is cuda 11-7,while cuda_home is 11.2, when I make the corrections, this problem fixed.

export CUDA_HOME=/usr/local/cuda-11.7
export PATH=/usr/local/cuda-11.7/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-11.7/lib64:$LD_LIBRARY_PATH
