### ISSUE TITLE
Installation Error. Cant compile some files, can anyone share the compiled files?

### ISSUE THREAD

**Issue by perfectFeng** [state-spaces/mamba#205]
Hello, I have encountered some installation problems on cuda11.2 and some files cant compiled. Have anyone compiled successfully and can share the files? The files and their addresses are

/mamba/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/selective_scan_bwd_bf16_complex.o
/mamba/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/selective_scan_bwd_bf16_real.o
/mamba/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/selective_scan_bwd_fp16_complex.o
/mamba/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/selective_scan_bwd_fp16_real.o
/mamba/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/selective_scan_bwd_fp32_complex.o
/mamba/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/selective_scan_bwd_fp32_real.o

**Comment by CompRhys** [comment]
If working in a conda environment a fairly decent solution attempt might be just to download cuda for nvidia's conda channel and then try again. To install you need as far as I understand to have a nvidia GPU with correct drivers both for this to work and to build mamba. 

```
conda install cuda -c nvidia
```

**Comment by perfectFeng** [comment]
> If working in a conda environment a fairly decent solution attempt might be just to download cuda for nvidia's conda channel and then try again. To install you need as far as I understand to have a nvidia GPU with correct drivers both for this to work and to build mamba.
> 
> ```
> conda install cuda -c nvidia
> ```

Thank you very much for your reply！

My system is cuda11.2, but I successfully installed cuda11.8 in the conda, my conda environment  is：
1.nvcc -V:
  nvcc: NVIDIA (R) Cuda compiler driver
  Copyright (c) 2005-2022 NVIDIA Corporation
  Built on Wed_Sep_21_10:33:58_PDT_2022
  Cuda compilation tools, release 11.8, V11.8.89
  Build cuda_11.8.r11.8/compiler.31833905_0
2.python --version
  Python 3.10.13
3. torch.__version__
  '2.1.1+cu118'

however, the error message cuda>11.6 was still reported during the installation. I cloned mamba locally and commented the cuda version requirements, that is:
if bare_metal_version < Version("11.6"):
            raise RuntimeError(
                f"{PACKAGE_NAME} is only supported on CUDA 11.6 and above.  "
                "Note: make sure nvcc has a supported version by running nvcc -V."
           )

But there is still a problem:
Traceback (most recent call last):
      File "~/.conda/envs/Mamba/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
        subprocess.run(
      File "~/.conda/envs/Mamba/lib/python3.10/subprocess.py", line 526, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

Do you know how to fixed it?
