### ISSUE TITLE
FileNotFoundError：exact_match.py not found！

### ISSUE THREAD

**Issue by qq1275012581** [state-spaces/mamba#215]
When I runned : 
```bash
python evals/lm_harness_eval.py --model mamba --model_args pretrained=state-spaces/mamba-130m --tasks lambada_openai,hellaswag,piqa,arc_easy,arc_challenge,winogrande --device cuda --batch_size 64
```
It would report an error:
> Traceback (most recent call last):
  File "evals/lm_harness_eval.py", line 8, in <module>
    from lm_eval.api.model import LM
  File "/public/home/ligw_sysu/mamba/3rdparty/lm-evaluation-harness/lm_eval/__init__.py", line 1, in <module>
    from .evaluator import evaluate, simple_evaluate
  File "/public/home/ligw_sysu/mamba/3rdparty/lm-evaluation-harness/lm_eval/evaluator.py", line 12, in <module>
    import lm_eval.tasks
  File "/public/home/ligw_sysu/mamba/3rdparty/lm-evaluation-harness/lm_eval/tasks/__init__.py", line 7, in <module>
    from lm_eval.api.task import TaskConfig, Task, ConfigurableTask
  File "/public/home/ligw_sysu/mamba/3rdparty/lm-evaluation-harness/lm_eval/api/task.py", line 27, in <module>
    from lm_eval.api.metrics import (
  File "/public/home/ligw_sysu/mamba/3rdparty/lm-evaluation-harness/lm_eval/api/metrics.py", line 139, in <module>
    exact_match = evaluate.load("exact_match")
  File "/public/home/ligw_sysu/anaconda3/envs/mamba/lib/python3.8/site-packages/evaluate/loading.py", line 748, in load
    evaluation_module = evaluation_module_factory(
  File "/public/home/ligw_sysu/anaconda3/envs/mamba/lib/python3.8/site-packages/evaluate/loading.py", line 681, in evaluation_module_factory
    raise FileNotFoundError(
FileNotFoundError: Couldn't find a module script at /public/home/ligw_sysu/mamba/exact_match/exact_match.py. Module 'exact_match' doesn't exist on the Hugging Face Hub either.
>
I looked at it, but I really didn't see the file on the above path. How can I solve it?

**Comment by haileyschoelkopf** [comment]
see: https://github.com/EleutherAI/lm-evaluation-harness/issues/1071

**Comment by qq1275012581** [comment]
> see: [EleutherAI/lm-evaluation-harness#1071](https://github.com/EleutherAI/lm-evaluation-harness/issues/1071)
Thank you for your response.
I will try the solutions here.  Thanks again！

**Comment by tridao** [comment]
I've changed the instruction in the README to use lm-eval from PyPI instead our own submodule, hopefully that fixes this issue.
