### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0`

### ISSUE THREAD

**Issue by yichenliuzong** [state-spaces/mamba#221]
A RuntimeError occurs when using the inference example given in README.md

The example in README.md is:
```
python benchmarks/benchmark_generation_mamba_simple.py --model-name "state-spaces/mamba-130m" --prompt "My cat wrote all this CUDA code for a new language model and" --minp 0.05 --topk 0 --temperature 0.7 --repetition-penalty 1.2
``` 

The issue is:
```
Traceback (most recent call last):
  File "/data/LiuYichen/mamba-main/benchmarks/benchmark_generation_mamba_simple.py", line 84, in <module>
    out = fn()
  File "/data/LiuYichen/mamba-main/benchmarks/benchmark_generation_mamba_simple.py", line 58, in <lambda>
    fn = lambda: model.generate(
  File "/data/LiuYichen/miniconda3/lib/python3.9/site-packages/mamba_ssm/utils/generation.py", line 260, in generate
    output = decode(
  File "/data/LiuYichen/miniconda3/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/LiuYichen/miniconda3/lib/python3.9/site-packages/mamba_ssm/utils/generation.py", line 229, in decode
    sampled_tokens = sample_tokens(logits, inference_params)
  File "/data/LiuYichen/miniconda3/lib/python3.9/site-packages/mamba_ssm/utils/generation.py", line 198, in sample_tokens
    token = sample(logits, top_k=top_k, top_p=top_p, min_p=min_p, temperature=temperature)
  File "/data/LiuYichen/miniconda3/lib/python3.9/site-packages/mamba_ssm/utils/generation.py", line 111, in sample
    return torch.multinomial(torch.softmax(logits_top, dim=-1), num_samples=1).squeeze(dim=-1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

**Comment by 41924076** [comment]
setting --topk 1 solve this problem for me
