### ISSUE TITLE
Problems with import mamba-ssm

### ISSUE THREAD

**Issue by yangtianjin** [state-spaces/mamba#248]
import mamba-ssm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/mount/data/ytj/anaconda3/envs/pytorch/lib/python3.10/site-packages/mamba_ssm/__init__.py", line 3, in <module>
    from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn
  File "/mnt/mount/data/ytj/anaconda3/envs/pytorch/lib/python3.10/site-packages/mamba_ssm/ops/selective_scan_interface.py", line 11, in <module>
    import selective_scan_cuda
ImportError: /mnt/mount/data/ytj/anaconda3/envs/pytorch/lib/python3.10/site-packages/selective_scan_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops10zeros_like4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEENS6_INS5_12MemoryFormatEEE

**Comment by pengzhangzhi** [comment]
same problem. In a nividia container... works well on the previous version of the mamba code.

**Comment by vincent317** [comment]
Downgrade to torch 2.2.2 works for me.
