### ISSUE TITLE
a problem when running "CAUSAL_CONV1D_FORCE_BUILD=TRUE pip install ."

### ISSUE THREAD

**Issue by Eraseryl** [state-spaces/mamba#323]
Processing /home/ubuntu/causal-conv1d
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/ubuntu/causal-conv1d/setup.py", line 103, in <module>
          raise RuntimeError(
      RuntimeError: causal_conv1d is only supported on CUDA 11.6 and above.  Note: make sure nvcc has a supported version by running nvcc -V.
      
      
      torch.__version__  = 2.1.0+cu121
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

my cuda version is 12.2
I've tried downloading .whl files and using pip install, no use though.

**Comment by Arkymeng** [comment]
I also have the same question

**Comment by tridao** [comment]
The error message says you need `nvcc`

**Comment by EngrUmerRamzan** [comment]
When I try to install mamba-ssm, got the following error on windows:

Collecting mamba-ssm==1.2.2
  Using cached mamba_ssm-1.2.2.tar.gz (35 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Gift Data Science\AppData\Local\Temp\pip-install-usaggt0t\mamba-ssm_9febe84898b74a8b9de4669470057d02\setup.py", line 101, in <module>
          _, bare_metal_version = get_cuda_bare_metal_version(CUDA_HOME)
        File "C:\Users\Gift Data Science\AppData\Local\Temp\pip-install-usaggt0t\mamba-ssm_9febe84898b74a8b9de4669470057d02\setup.py", line 63, in get_cuda_bare_metal_version
          raw_output = subprocess.check_output(
        File "C:\Users\Gift Data Science\.conda\envs\crimsniffer\lib\subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\Gift Data Science\.conda\envs\crimsniffer\lib\subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\Gift Data Science\.conda\envs\crimsniffer\lib\subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\Gift Data Science\.conda\envs\crimsniffer\lib\subprocess.py", line 1436, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified


      torch.__version__  = 2.2.1+cu118


      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by tridao** [comment]
Sorry idk much about windows

**Comment by ZhangLiyuan11** [comment]
> 当我尝试安装 mamba-ssm 时，在 Windows 上出现以下错误：
> 
> 收集 mamba-ssm==1.2.2 使用缓存mamba_ssm-1.2.2.tar.gz （35 kB） 准备元数据 （setup.py） ...错误错误：subprocess-exited-with-error
> 
> × python setup.py egg_info 未成功运行。 │ 退出代码： 1 ╰─> [21 行输出] 回溯（最近一次调用最后）： 文件 “”，第 2 行，在文件 “”“中，第 34 行，在文件”C：\Users\Gift Data Science\AppData\Local\Temp\pip-install-usaggt0t\mamba-ssm_9febe84898b74a8b9de4669470057d02\setup.py“中，第 101 行，在 _ 中，bare_metal_version = get_cuda_bare_metal_version（CUDA_HOME）文件“C：\Users\Gift Data Science\AppData\Local\Temp\pip-install-usaggt0t\mamba-ssm_9febe84898b74a8b9de4669470057d02\setup.py”，第 63 行，在 get_cuda_bare_metal_version raw_output = subprocess.check_output（ 文件“C：\Users\Gift Data Science.conda\envs\crimsniffer\lib\subprocess.py”，第 424 行，在 check_output return run（*popenargs， stdout=PIPE， timeout=timeout， check=True，文件“C：\Users\Gift Data Science.conda\envs\crimsniffer\lib\subprocess.py”，第 505 行，使用 Popen（*popenargs， **kwargs） 作为进程运行：文件“C：\Users\Gift Data Science.conda\envs\crimsniffer\lib\subprocess.py”，第 951 行，**init** self._execute_child（args，可执行文件，preexec_fn，close_fds，文件“C：\Users\Gift Data Science.conda\envs\crimsniffer\lib\subprocess.py”，第 1436 行，_execute_childhp、ht、pid、tid = _winapi。CreateProcess（可执行文件， args， FileNotFoundError： [WinError 2] 系统找不到指定的文件
> 
> ```
>   torch.__version__  = 2.2.1+cu118
> 
> 
>   [end of output]
> ```
> 
> 注意：此错误源自子进程，可能不是 pip 的问题。错误：元数据生成失败
> 
> × 生成包元数据时遇到错误。 ╰─> 输出见上文。
> 
> 注意：这是上面提到的软件包的问题，而不是 pip。提示：有关详细信息，请参阅上文。

I have the same problem as you, please can you solve it
