### ISSUE TITLE
RuntimeError while trying to run MambaLMHeadModel

### ISSUE THREAD

**Issue by ph-marra** [state-spaces/mamba#325]
**Background**: ran successfully the simple example `Mamba`  (no problem using the Mamba mixer) found at README using the environment (pip+conda) suggested in #277 [here](https://github.com/state-spaces/mamba/issues/277#issuecomment-2049599198).

Hi, I'm currently trying to run `MambaLMHeadModel` (mixer found in [mamba_ssm/models/mixer_seq_simple.py](https://github.com/state-spaces/mamba/blob/main/mamba_ssm/models/mixer_seq_simple.py)) on a simple example (similar to the README one) but I'm encountering some problems:

```
import torch
from mamba_ssm import MambaLMHeadModel
from mamba_ssm.models.config_mamba import MambaConfig

config = MambaConfig()
batch, length = 2, 64
x = torch.randn(batch, length, device='cuda')
model = MambaLMHeadModel(
    config=config,
    device='cuda:0'
)

y = model(x)
```

Got the following error:

```
Traceback (most recent call last):
  File "/home/pedro/mamba/teste.py", line 69, in <module>
    y = model(x)
  File "/workspace/anaconda3/envs/MambaLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/anaconda3/envs/MambaLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/anaconda3/envs/MambaLM/lib/python3.10/site-packages/mamba_ssm/models/mixer_seq_simple.py", line 234, in forward
    hidden_states = self.backbone(input_ids, inference_params=inference_params)
  File "/workspace/anaconda3/envs/MambaLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/anaconda3/envs/MambaLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/anaconda3/envs/MambaLM/lib/python3.10/site-packages/mamba_ssm/models/mixer_seq_simple.py", line 152, in forward
    hidden_states = self.embedding(input_ids)
  File "/workspace/anaconda3/envs/MambaLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/anaconda3/envs/MambaLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/anaconda3/envs/MambaLM/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/workspace/anaconda3/envs/MambaLM/lib/python3.10/site-packages/torch/nn/functional.py", line 2233, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)
while running the model.
```

Any idea of what am I doing wrong? Already tried to run mamba-ssm locally (another error with the SSM operation done in [mamba_ssm/models/ops/selective_scan_cuda](https://github.com/state-spaces/mamba/blob/main/mamba_ssm/ops/selective_scan_interface.py)), but also with no avail. Also thought about typecasting before running the model, yet the same error.

**Comment by BlenderWang9487** [comment]
Hi, 

Please look at the model's forward function argument first.

It appears that the issue you're encountering is due to the type of tensor being passed to the `forward` method of the `MambaLMHeadModel`. Specifically, the first argument `input_ids` is expected to be an integer tensor, but you are providing a floating point tensor generated by `torch.randn`.

To resolve this, you should use an integer tensor as input. You can modify your code as follows to use random integers within a valid range instead of floating point values:

```python
import torch
from mamba_ssm import MambaLMHeadModel
from mamba_ssm.models.config_mamba import MambaConfig

config = MambaConfig()
batch, length = 2, 64

# Use random integers within a specific range
x = torch.randint(0, config.vocab_size, (batch, length), device='cuda:0')

model = MambaLMHeadModel(
    config=config,
    device='cuda:0'
)

y = model(x)
```

**Comment by ph-marra** [comment]
Hi @BlenderWang9487, thanks for the quick response. Now I understand where I went wrong.
