### ISSUE TITLE
mamba_ssm安装成功，导入失败，无法使用。

### ISSUE THREAD

**Issue by Lijuming33** [state-spaces/mamba#338]
>>> from mamba_ssm import Mamba
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/deng/miniforge-pypy3/envs/mamba/lib/python3.10/site-packages/mamba_ssm/__init__.py", line 3, in <module>
    from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn
  File "/home/deng/miniforge-pypy3/envs/mamba/lib/python3.10/site-packages/mamba_ssm/ops/selective_scan_interface.py", line 16, in <module>
    import selective_scan_cuda
ImportError: /home/deng/miniforge-pypy3/envs/mamba/lib/python3.10/site-packages/selective_scan_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
>>>
![image](https://github.com/state-spaces/mamba/assets/74756259/c6f21023-94d1-4ad6-8d0d-77a5852b0a71)

wsl2 Ubuntu22.04，gcc>>>11.4
我的cuda版本为11.8，torch=2.3
CUDA11.8为https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda_11.8.0_520.61.05_linux.run
安装方式为torch安装方式为：
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

**Comment by catalpaaa** [comment]
you should clone the repo down and install it with pip -e, same for conv1d

**Comment by Jon-Zbw** [comment]
> > > > from mamba_ssm import Mamba
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/home/deng/miniforge-pypy3/envs/mamba/lib/python3.10/site-packages/mamba_ssm/**init**.py", line 3, in 
> > > > from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn
> > > > File "/home/deng/miniforge-pypy3/envs/mamba/lib/python3.10/site-packages/mamba_ssm/ops/selective_scan_interface.py", line 16, in 
> > > > import selective_scan_cuda
> > > > ImportError: /home/deng/miniforge-pypy3/envs/mamba/lib/python3.10/site-packages/selective_scan_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
> 
> ![image](https://private-user-images.githubusercontent.com/74756259/335609865-c6f21023-94d1-4ad6-8d0d-77a5852b0a71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTQ3NjIsIm5iZiI6MTcyNDA1NDQ2MiwicGF0aCI6Ii83NDc1NjI1OS8zMzU2MDk4NjUtYzZmMjEwMjMtOTRkMS00YWQ2LThkMGQtNzdhNTg1MmIwYTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDA4MDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NjMzN2Y5Nzg2NGJkNGY5OGExZDU3YjVkNGY4ZGQzYTU1YTJkOGU1MzFjYjhlMTAxOGM4YjdjNTAyNTE5MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0d5BjxeSubaVmBQEjfNAv-vfogJBA__EVhAxbGoFxIY)
> 
> wsl2 Ubuntu22.04，gcc>>>11.4 我的cuda版本为11.8，torch=2.3 CUDA11.8为https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda_11.8.0_520.61.05_linux.run 安装方式为torch安装方式为： pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

are you solved????
