### ISSUE TITLE
AssertionError exclusive to Mamba2

### ISSUE THREAD

**Issue by Madiwka4** [state-spaces/mamba#347]
When using

`        Mamba2(
            d_model=dim,  
            d_state=64,  
            d_conv=4, 
            expand=2)`
I receive the following error:

> File mamba2.py
>      assert ngroups % self.world_size == 0
>      self.ngroups = ngroups // self.world_size
> ---> assert self.d_ssm % self.headdim == 0
>      self.nheads = self.d_ssm // self.headdim
>      self.D_has_hdim = D_has_hdim
> 
> AssertionError:

However, this error is not present when running normal Mamba.

**Comment by hanif-rt** [comment]
Seems to work with `dim=1024` for me.

**Comment by gaotai8** [comment]
> `dim=1024`似乎对我 有用。`Mamba2( d_model=1024, d_state=64, d_conv=4, expand=2)`
> 
> [Tri Dao 在另一个线程](https://github.com/state-spaces/mamba/issues/345)中的注释： --Mamba2 仅使用 dim_model 的 512 倍数进行了测试。

yes,you are right.but there is also a error when i y = model(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gaotai/conda/ENTER/envs/mamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/modules/mamba2.py", line 176, in forward
    out = mamba_split_conv1d_scan_combined(
  File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/ops/triton/ssd_combined.py", line 908, in mamba_split_conv1d_scan_combined
    return MambaSplitConv1dScanCombinedFn.apply(zxbcdt, conv1d_weight, conv1d_bias, dt_bias, A, D, chunk_size, initial_states, seq_idx, dt_limit, return_final_states, activation, rmsnorm_weight, rmsnorm_eps, outproj_weight, outproj_bias, headdim, ngroups, norm_before_gate)
  File "/home/gaotai/conda/ENTER/envs/mamba/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 97, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/ops/triton/ssd_combined.py", line 757, in forward
    causal_conv1d_cuda.causal_conv1d_fwd(rearrange(xBC, "b s d -> b d s"),
AttributeError: 'NoneType' object has no attribute 'causal_conv1d_fwd'

**Comment by huangwenjunlovedy** [comment]
> Seems to work with `dim=1024` for me. `Mamba2( d_model=1024, d_state=64, d_conv=4, expand=2)`
> 
> Note from Tri Dao in [another thread](https://github.com/state-spaces/mamba/issues/345): -- Mamba2 has only been tested with dim_model multiples of 512.

thank you！

**Comment by nican2018** [comment]
> > `dim=1024`似乎对我 有用。`Mamba2( d_model=1024, d_state=64, d_conv=4, expand=2)`
> > [Tri Dao 在另一个线程](https://github.com/state-spaces/mamba/issues/345)中的注释： --Mamba2 仅使用 dim_model 的 512 倍数进行了测试。
> 
> yes,you are right.but there is also a error when i y = model(x) Traceback (most recent call last): File "", line 1, in File "/home/gaotai/conda/ENTER/envs/mamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/modules/mamba2.py", line 176, in forward out = mamba_split_conv1d_scan_combined( File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/ops/triton/ssd_combined.py", line 908, in mamba_split_conv1d_scan_combined return MambaSplitConv1dScanCombinedFn.apply(zxbcdt, conv1d_weight, conv1d_bias, dt_bias, A, D, chunk_size, initial_states, seq_idx, dt_limit, return_final_states, activation, rmsnorm_weight, rmsnorm_eps, outproj_weight, outproj_bias, headdim, ngroups, norm_before_gate) File "/home/gaotai/conda/ENTER/envs/mamba/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 97, in decorate_fwd return fwd(*args, **kwargs) File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/ops/triton/ssd_combined.py", line 757, in forward causal_conv1d_cuda.causal_conv1d_fwd(rearrange(xBC, "b s d -> b d s"), AttributeError: 'NoneType' object has no attribute 'causal_conv1d_fwd'

Please have you solve this problem?

**Comment by JinxiaXie** [comment]
> > `dim=1024`似乎对我 有用。`Mamba2( d_model=1024, d_state=64, d_conv=4, expand=2)`
> > [Tri Dao 在另一个线程](https://github.com/state-spaces/mamba/issues/345)中的注释： --Mamba2 仅使用 dim_model 的 512 倍数进行了测试。
> 
> yes,you are right.but there is also a error when i y = model(x) Traceback (most recent call last): File "", line 1, in File "/home/gaotai/conda/ENTER/envs/mamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/modules/mamba2.py", line 176, in forward out = mamba_split_conv1d_scan_combined( File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/ops/triton/ssd_combined.py", line 908, in mamba_split_conv1d_scan_combined return MambaSplitConv1dScanCombinedFn.apply(zxbcdt, conv1d_weight, conv1d_bias, dt_bias, A, D, chunk_size, initial_states, seq_idx, dt_limit, return_final_states, activation, rmsnorm_weight, rmsnorm_eps, outproj_weight, outproj_bias, headdim, ngroups, norm_before_gate) File "/home/gaotai/conda/ENTER/envs/mamba/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 97, in decorate_fwd return fwd(*args, **kwargs) File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/ops/triton/ssd_combined.py", line 757, in forward causal_conv1d_cuda.causal_conv1d_fwd(rearrange(xBC, "b s d -> b d s"), AttributeError: 'NoneType' object has no attribute 'causal_conv1d_fwd'

I have the same question.

**Comment by arelkeselbri** [comment]
I found the same issue and solved using:

pip install causal-conv1d>=1.2.0

Em qua., 5 de jun. de 2024 às 10:07, xjx ***@***.***>
escreveu:

**Comment by liuquangao** [comment]
pip install causal-conv1d>=1.2.0

> > > `dim=1024`似乎对我 有用。`Mamba2( d_model=1024, d_state=64, d_conv=4, expand=2)`
> > > [Tri Dao 在另一个线程](https://github.com/state-spaces/mamba/issues/345)中的注释： --Mamba2 仅使用 dim_model 的 512 倍数进行了测试。
> > 
> > 
> > yes,you are right.but there is also a error when i y = model(x) Traceback (most recent call last): File "", line 1, in File "/home/gaotai/conda/ENTER/envs/mamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/modules/mamba2.py", line 176, in forward out = mamba_split_conv1d_scan_combined( File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/ops/triton/ssd_combined.py", line 908, in mamba_split_conv1d_scan_combined return MambaSplitConv1dScanCombinedFn.apply(zxbcdt, conv1d_weight, conv1d_bias, dt_bias, A, D, chunk_size, initial_states, seq_idx, dt_limit, return_final_states, activation, rmsnorm_weight, rmsnorm_eps, outproj_weight, outproj_bias, headdim, ngroups, norm_before_gate) File "/home/gaotai/conda/ENTER/envs/mamba/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 97, in decorate_fwd return fwd(*args, **kwargs) File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/ops/triton/ssd_combined.py", line 757, in forward causal_conv1d_cuda.causal_conv1d_fwd(rearrange(xBC, "b s d -> b d s"), AttributeError: 'NoneType' object has no attribute 'causal_conv1d_fwd'
> 
> I have this problem ,too.Please have your solved this problem?

try `pip install causal-conv1d>=1.2.0`

**Comment by 7unahan** [comment]
> pip install causal-conv1d>=1.2.0
> 
> > > > `dim=1024`似乎对我 有用。`Mamba2( d_model=1024, d_state=64, d_conv=4, expand=2)`
> > > > [Tri Dao 在另一个线程](https://github.com/state-spaces/mamba/issues/345)中的注释： --Mamba2 仅使用 dim_model 的 512 倍数进行了测试。
> > > 
> > > 
> > > yes,you are right.but there is also a error when i y = model(x) Traceback (most recent call last): File "", line 1, in File "/home/gaotai/conda/ENTER/envs/mamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/modules/mamba2.py", line 176, in forward out = mamba_split_conv1d_scan_combined( File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/ops/triton/ssd_combined.py", line 908, in mamba_split_conv1d_scan_combined return MambaSplitConv1dScanCombinedFn.apply(zxbcdt, conv1d_weight, conv1d_bias, dt_bias, A, D, chunk_size, initial_states, seq_idx, dt_limit, return_final_states, activation, rmsnorm_weight, rmsnorm_eps, outproj_weight, outproj_bias, headdim, ngroups, norm_before_gate) File "/home/gaotai/conda/ENTER/envs/mamba/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 97, in decorate_fwd return fwd(*args, **kwargs) File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/ops/triton/ssd_combined.py", line 757, in forward causal_conv1d_cuda.causal_conv1d_fwd(rearrange(xBC, "b s d -> b d s"), AttributeError: 'NoneType' object has no attribute 'causal_conv1d_fwd'
> > 
> > 
> > I have this problem ,too.Please have your solved this problem?
> 
> try `pip install causal-conv1d`

I tried this one, did not solve my problem.

**Comment by Wietc** [comment]
> > pip install causal-conv1d>=1.2.0
> > > > > `dim=1024`似乎对我 有用。`Mamba2( d_model=1024, d_state=64, d_conv=4, expand=2)`
> > > > > [Tri Dao 在另一个线程](https://github.com/state-spaces/mamba/issues/345)中的注释： --Mamba2 仅使用 dim_model 的 512 倍数进行了测试。
> > > > 
> > > > 
> > > > yes,you are right.but there is also a error when i y = model(x) Traceback (most recent call last): File "", line 1, in File "/home/gaotai/conda/ENTER/envs/mamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/modules/mamba2.py", line 176, in forward out = mamba_split_conv1d_scan_combined( File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/ops/triton/ssd_combined.py", line 908, in mamba_split_conv1d_scan_combined return MambaSplitConv1dScanCombinedFn.apply(zxbcdt, conv1d_weight, conv1d_bias, dt_bias, A, D, chunk_size, initial_states, seq_idx, dt_limit, return_final_states, activation, rmsnorm_weight, rmsnorm_eps, outproj_weight, outproj_bias, headdim, ngroups, norm_before_gate) File "/home/gaotai/conda/ENTER/envs/mamba/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 97, in decorate_fwd return fwd(*args, **kwargs) File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/ops/triton/ssd_combined.py", line 757, in forward causal_conv1d_cuda.causal_conv1d_fwd(rearrange(xBC, "b s d -> b d s"), AttributeError: 'NoneType' object has no attribute 'causal_conv1d_fwd'
> > > 
> > > 
> > > I have this problem ,too.Please have your solved this problem?
> > 
> > 
> > try `pip install causal-conv1d`
> 
> I tried this one, did not solve my problem.

I have the same issue in my code, when I tried to use Mamba2 Block instead of Mamba Block.
You can try to use `pip install causal-conv1d>=1.2.0`
It works for me!

**Comment by drishyakarki** [comment]
Hi, I tried both ```pip install causal-conv1d``` and ```pip install causal-conv1d>=1.2.0```. I am still getting this error


```Traceback (most recent call last):
  File "/home/drishya/Desktop/mamba/test.py", line 13, in <module>
    y = model(x)
        ^^^^^^^^
  File "/home/drishya/Desktop/mamba/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drishya/Desktop/mamba/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drishya/Desktop/mamba/mamba_ssm/modules/mamba2.py", line 177, in forward
    out = mamba_split_conv1d_scan_combined(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drishya/Desktop/mamba/mamba_ssm/ops/triton/ssd_combined.py", line 912, in mamba_split_conv1d_scan_combined
    return MambaSplitConv1dScanCombinedFn.apply(zxbcdt, conv1d_weight, conv1d_bias, dt_bias, A, D, chunk_size, initial_states, seq_idx, dt_limit, return_final_states, activation, rmsnorm_weight, rmsnorm_eps, outproj_weight, outproj_bias, headdim, ngroups, norm_before_gate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drishya/Desktop/mamba/venv/lib/python3.12/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drishya/Desktop/mamba/venv/lib/python3.12/site-packages/torch/cuda/amp/autocast_mode.py", line 115, in decorate_fwd
    return fwd(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/drishya/Desktop/mamba/mamba_ssm/ops/triton/ssd_combined.py", line 761, in forward
    causal_conv1d_cuda.causal_conv1d_fwd(rearrange(xBC, "b s d -> b d s"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'causal_conv1d_fwd'
```

**Comment by Zhou-CyberSecurity-AI** [comment]
> > > `dim=1024`似乎对我 有用。`Mamba2( d_model=1024, d_state=64, d_conv=4, expand=2)`
> > > [Tri Dao 在另一个线程](https://github.com/state-spaces/mamba/issues/345)中的注释： --Mamba2 仅使用 dim_model 的 512 倍数进行了测试。
> > 
> > 
> > yes,you are right.but there is also a error when i y = model(x) Traceback (most recent call last): File "", line 1, in File "/home/gaotai/conda/ENTER/envs/mamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/modules/mamba2.py", line 176, in forward out = mamba_split_conv1d_scan_combined( File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/ops/triton/ssd_combined.py", line 908, in mamba_split_conv1d_scan_combined return MambaSplitConv1dScanCombinedFn.apply(zxbcdt, conv1d_weight, conv1d_bias, dt_bias, A, D, chunk_size, initial_states, seq_idx, dt_limit, return_final_states, activation, rmsnorm_weight, rmsnorm_eps, outproj_weight, outproj_bias, headdim, ngroups, norm_before_gate) File "/home/gaotai/conda/ENTER/envs/mamba/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 97, in decorate_fwd return fwd(*args, **kwargs) File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/ops/triton/ssd_combined.py", line 757, in forward causal_conv1d_cuda.causal_conv1d_fwd(rearrange(xBC, "b s d -> b d s"), AttributeError: 'NoneType' object has no attribute 'causal_conv1d_fwd'
> 
> I have the same question.

I also have the same question.

**Comment by ly510244856** [comment]
> > > > `dim=1024``Mamba2( d_model=1024, d_state=64, d_conv=4, expand=2)`
> > > > [Tri Dao 在另一个线程](https://github.com/state-spaces/mamba/issues/345)中的注释： --Mamba2 仅使用dim_model 的 512 倍数进行了测试。
> > > 
> > > 
> > > 是的，你是对的。但是当 iy = model(x) 时也会出现错误 Traceback (most recent call last): File "", line 1, in File "/home/gaotai/conda/ENTER/envs/mamba/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/modules/mamba2.py", line 176, in forward out = mamba_split_conv1d_scan_combined( File "/home/gaotai/project/mamba-2.0.3/mamba_ssm/ops/triton/ssd_combined.py", line 908, in mamba_split_conv1d_scan_combined return MambaSplitConv1dScanCombinedFn.apply(zxbcdt, conv1d_weight, conv1d_bias, dt_bias, A, D, chunk_size, initial_states, seq_idx, dt_limit, return_final_states, activity, rmsnorm_weight, rmsnorm_eps, outproj_weight, outproj_bias, headdim, ngroups, norm_before_gate) 文件“/home/gaotai/conda/ENTER/envs/mamba/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py”，第 97 行，在 decorate_fwd 中返回 fwd(*args, **kwargs)文件“/home/gaotai/project/mamba-2.0.3/mamba_ssm/ops/triton/ssd_combined.py”，第 757 行，在正向 causal_conv1d_cuda.causal_conv1d_fwd(rearrange(xBC, “bsd -> bd s”)，AttributeError: 'NoneType' 对象没有属性 'causal_conv1d_fwd'
> > 
> > 
> > 我也有同样的问题。
> 
> 我也有同样的问题。

Visit the link https://github.com/Dao-AILab/causal-conv1d/releases to download the .whl file. I used the [causal_conv1d-1.4.0+cu118torch2.2cxx11abiFALSE-cp310-cp310-linux_x86_64.whl](https://github.com/Dao-AILab/causal-conv1d/releases/download/v1.4.0/causal_conv1d-1.4.0+cu118torch2.2cxx11abiFALSE-cp310-cp310-linux_x86_64.whl) version. The "abiFALSE" version might be more useful.
