### ISSUE TITLE
where is the src.ops.triton.k_activations?

### ISSUE THREAD

**Issue by gaotai8** [state-spaces/mamba#349]
>>> import torch
>>> from mamba_ssm import Mamba
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gaotai/project/mamba/mamba_ssm/__init__.py", line 5, in <module>
    from mamba_ssm.modules.mamba2 import Mamba2
  File "/home/gaotai/project/mamba/mamba_ssm/modules/mamba2.py", line 26, in <module>
    from mamba_ssm.ops.triton.ssd_combined import mamba_chunk_scan_combined
  File "/home/gaotai/project/mamba/mamba_ssm/ops/triton/ssd_combined.py", line 40, in <module>
    from src.ops.triton.k_activations import _swiglu_fwd, _swiglu_bwd
ModuleNotFoundError: No module named 'src.ops.triton.k_activations'

**Comment by jpilaul** [comment]
Should be here: `https://github.com/state-spaces/mamba/blob/main/mamba_ssm/ops/triton/k_activations.py`

**Comment by gaotai8** [comment]
> 应该在这里：`https://github.com/state-spaces/mamba/blob/main/mamba_ssm/ops/triton/k_activations.py`

thank you.we can download v2.3.0
