### ISSUE TITLE
Mamba2 using Triton 2.1.0 error: FileNotFoundError: [Errno 2] No such file or directory: 'ldconfig'

### ISSUE THREAD

**Issue by Mang30** [state-spaces/mamba#363]
I encountered some errors while using Mamba2 and tried to resolve them without success, so I would like to ask for your opinions and insights. Thank you in advance!

Description: The operating system I am using is Ubuntu 20.04, the GPU is an A10, the NVIDIA driver version is 515.65.01, and the CUDA version is 11.7.1

#### 1. Here is my code:

```
import torch
from mamba2.mamba_ssm import Mamba2 as Mamba

batch, length, dim = 2, 64, 1024
x = torch.randn(batch, length, dim).to("cuda")
model = Mamba(
    # This module uses roughly 3 * expand * d_model^2 parameters
    d_model=dim, # Model dimension d_model
    d_state=16,  # SSM state expansion factor
    d_conv=4,    # Local convolution width
    expand=2,    # Block expansion factor
).to("cuda")
y = model(x)
assert y.shape == x.shape
```
> 

#### 2. Here is the error message I received:

```
/home/zkpk/micromamba/envs/20240604/bin/python /home/zkpk/PycharmProjects/huggingface_model/mamba2/mamba2_test.py 
self.headdim: 64
self.d_ssm: 2048
Traceback (most recent call last):
  File "/home/zkpk/PycharmProjects/huggingface_model/mamba2/mamba2_test.py", line 42, in <module>
    y = model(x)
  File "/home/zkpk/micromamba/envs/scgpt_20240604/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zkpk/PycharmProjects/huggingface_model/mamba2/mamba_ssm/modules/mamba2.py", line 178, in forward
    out = mamba_split_conv1d_scan_combined(
  File "/home/zkpk/PycharmProjects/huggingface_model/mamba2/mamba_ssm/ops/triton/ssd_combined.py", line 910, in mamba_split_conv1d_scan_combined
    return MambaSplitConv1dScanCombinedFn.apply(zxbcdt, conv1d_weight, conv1d_bias, dt_bias, A, D, chunk_size, initial_states, seq_idx, dt_limit, return_final_states, activation, rmsnorm_weight, rmsnorm_eps, outproj_weight, outproj_bias, headdim, ngroups, norm_before_gate)
  File "/home/zkpk/micromamba/envs/scgpt_20240604/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 97, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/zkpk/PycharmProjects/huggingface_model/mamba2/mamba_ssm/ops/triton/ssd_combined.py", line 774, in forward
    out_x, _, dt_out, dA_cumsum, states, final_states = _mamba_chunk_scan_combined_fwd(x, dt, A, B, C, chunk_size=chunk_size, D=D, z=None, dt_bias=dt_bias, initial_states=initial_states, seq_idx=seq_idx, dt_softplus=True, dt_limit=dt_limit)
  File "/home/zkpk/PycharmProjects/huggingface_model/mamba2/mamba_ssm/ops/triton/ssd_combined.py", line 307, in _mamba_chunk_scan_combined_fwd
    dA_cumsum, dt = _chunk_cumsum_fwd(dt, A, chunk_size, dt_bias=dt_bias, dt_softplus=dt_softplus, dt_limit=dt_limit)
  File "/home/zkpk/PycharmProjects/huggingface_model/mamba2/mamba_ssm/ops/triton/ssd_chunk_state.py", line 582, in _chunk_cumsum_fwd
    _chunk_cumsum_fwd_kernel[grid_chunk_cs](
  File "/home/zkpk/micromamba/envs/scgpt_20240604/lib/python3.9/site-packages/triton/runtime/autotuner.py", line 100, in run
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/home/zkpk/micromamba/envs/scgpt_20240604/lib/python3.9/site-packages/triton/runtime/autotuner.py", line 100, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/home/zkpk/micromamba/envs/scgpt_20240604/lib/python3.9/site-packages/triton/runtime/autotuner.py", line 83, in _bench
    return do_bench(kernel_call, warmup=self.warmup, rep=self.rep, quantiles=(0.5, 0.2, 0.8))
  File "/home/zkpk/micromamba/envs/scgpt_20240604/lib/python3.9/site-packages/triton/testing.py", line 104, in do_bench
    fn()
  File "/home/zkpk/micromamba/envs/scgpt_20240604/lib/python3.9/site-packages/triton/runtime/autotuner.py", line 81, in kernel_call
    self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages, **current)
  File "<string>", line 63, in _chunk_cumsum_fwd_kernel
  File "/home/zkpk/micromamba/envs/scgpt_20240604/lib/python3.9/site-packages/triton/compiler/compiler.py", line 425, in compile
    so_path = make_stub(name, signature, constants)
  File "/home/zkpk/micromamba/envs/scgpt_20240604/lib/python3.9/site-packages/triton/compiler/make_launcher.py", line 39, in make_stub
    so = _build(name, src_path, tmpdir)
  File "/home/zkpk/micromamba/envs/scgpt_20240604/lib/python3.9/site-packages/triton/common/build.py", line 61, in _build
    cuda_lib_dirs = libcuda_dirs()
  File "/home/zkpk/micromamba/envs/scgpt_20240604/lib/python3.9/site-packages/triton/common/build.py", line 21, in libcuda_dirs
    libs = subprocess.check_output(["ldconfig", "-p"]).decode()
  File "/home/zkpk/micromamba/envs/scgpt_20240604/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/zkpk/micromamba/envs/scgpt_20240604/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/zkpk/micromamba/envs/scgpt_20240604/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/zkpk/micromamba/envs/scgpt_20240604/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ldconfig'
```

#### 3.Here is my conda environment:

```
pip list
Package                   Version
------------------------- ---------------------
absl-py                   2.1.0
aiohttp                   3.9.5
aiosignal                 1.3.1
anndata                   0.10.5.post1
anyio                     4.4.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
array_api_compat          1.7.1
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
async-timeout             4.0.3
attrs                     23.2.0
Babel                     2.15.0
beautifulsoup4            4.12.3
bleach                    6.1.0
cached-property           1.5.2
cachetools                5.3.3
causal-conv1d             1.2.1
certifi                   2024.6.2
cffi                      1.16.0
charset-normalizer        3.3.2
chex                      0.1.6
click                     8.1.7
cmake                     3.29.3
colorama                  0.4.6
comm                      0.2.2
commonmark                0.9.1
contourpy                 1.2.1
cycler                    0.12.1
datasets                  2.3.2
dcor                      0.6
debugpy                   1.8.1
decorator                 5.1.1
defusedxml                0.7.1
Deprecated                1.2.14
dill                      0.3.5.1
dm-tree                   0.1.8
docker-pycreds            0.4.0
docrep                    0.3.2
einops                    0.8.0
et-xmlfile                1.1.0
etils                     1.5.2
exceptiongroup            1.2.1
executing                 2.0.1
fastjsonschema            2.19.1
filelock                  3.14.0
flash_attn                1.0.4
flax                      0.5.3
fonttools                 4.53.0
fqdn                      1.5.1
frozenlist                1.4.1
fsspec                    2024.6.0
future                    1.0.0
gitdb                     4.0.11
GitPython                 3.1.43
google-auth               2.29.0
google-auth-oauthlib      0.4.6
grpcio                    1.64.1
h11                       0.14.0
h5py                      3.11.0
httpcore                  1.0.5
httpx                     0.27.0
huggingface-hub           0.23.2
idna                      3.7
igraph                    0.11.5
importlib_metadata        7.1.0
importlib_resources       6.4.0
iniconfig                 2.0.0
ipykernel                 6.29.4
ipython                   8.18.1
ipywidgets                8.1.3
isoduration               20.11.0
jax                       0.3.15
jaxlib                    0.3.15+cuda11.cudnn82
jedi                      0.19.1
Jinja2                    3.1.4
joblib                    1.4.2
json5                     0.9.25
jsonpointer               2.4
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
jupyter                   1.0.0
jupyter_client            8.6.2
jupyter-console           6.6.3
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter-lsp               2.2.5
jupyter_server            2.14.1
jupyter_server_terminals  0.5.3
jupyterlab                4.2.1
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.2
jupyterlab_widgets        3.0.11
kiwisolver                1.4.5
leidenalg                 0.10.2
llvmlite                  0.38.1
mamba-ssm                 1.2.1
Markdown                  3.6
MarkupSafe                2.1.5
matplotlib                3.6.0
matplotlib-inline         0.1.7
mistune                   3.0.2
ml-dtypes                 0.4.0
msgpack                   1.0.8
multidict                 6.0.5
multipledispatch          1.0.0
multiprocess              0.70.13
natsort                   8.4.0
nbclient                  0.10.0
nbconvert                 7.16.4
nbformat                  5.10.4
nest-asyncio              1.6.0
networkx                  3.2.1
ninja                     1.11.1.1
notebook                  7.2.0
notebook_shim             0.2.4
numba                     0.55.2
numpy                     1.21.6
numpyro                   0.10.1
oauthlib                  3.2.2
openpyxl                  3.1.3
opt-einsum                3.3.0
optax                     0.1.2
orbax                     0.1.0
overrides                 7.7.0
packaging                 24.0
pandas                    1.3.5
pandocfilters             1.5.1
parso                     0.8.4
patsy                     0.5.6
pexpect                   4.9.0
pillow                    10.3.0
pip                       24.0
platformdirs              4.2.2
pluggy                    1.5.0
prometheus_client         0.20.0
prompt_toolkit            3.0.45
protobuf                  3.20.1
psutil                    5.9.8
ptyprocess                0.7.0
pure-eval                 0.2.2
pyarrow                   16.1.0
pyasn1                    0.6.0
pyasn1_modules            0.4.0
pycparser                 2.22
pyDeprecate               0.3.1
pydot                     2.0.0
Pygments                  2.18.0
pynndescent               0.5.12
pyparsing                 3.1.2
pyro-api                  0.1.2
pyro-ppl                  1.8.6
pytest                    8.2.1
python-dateutil           2.9.0.post0
python-json-logger        2.0.7
pytorch-lightning         1.5.10
pytz                      2024.1
PyYAML                    6.0.1
pyzmq                     26.0.3
qtconsole                 5.5.2
QtPy                      2.4.1
referencing               0.35.1
regex                     2024.5.15
requests                  2.32.3
requests-oauthlib         2.0.0
responses                 0.18.0
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rich                      11.2.0
rpds-py                   0.18.1
rsa                       4.9
safetensors               0.4.3
scanpy                    1.9.1
scib                      1.1.4
scikit-learn              1.5.0
scikit-misc               0.1.4
scipy                     1.11.4
scvi-tools                0.16.4
seaborn                   0.13.2
Send2Trash                1.8.3
sentry-sdk                2.4.0
session_info              1.0.0
setproctitle              1.3.3
setuptools                59.5.0
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
soupsieve                 2.5
stack-data                0.6.3
statsmodels               0.14.1
stdlib-list               0.10.0
tensorboard               2.8.0
tensorboard-data-server   0.6.1
tensorboard-plugin-wit    1.8.1
tensorstore               0.1.60
terminado                 0.18.1
texttable                 1.7.0
threadpoolctl             3.5.0
tinycss2                  1.3.0
tokenizers                0.19.1
tomli                     2.0.1
toolz                     0.12.1
torch                     1.13.1+cu117
torchaudio                0.13.1+cu117
torchmetrics              0.9.1
torchtext                 0.14.1
torchvision               0.14.1+cu117
tornado                   6.4
tqdm                      4.66.4
traitlets                 5.14.3
transformers              4.41.2
triton                    2.1.0
types-python-dateutil     2.9.0.20240316
typing_extensions         4.12.1
umap-learn                0.5.6
uri-template              1.3.0
urllib3                   2.2.1
wandb                     0.17.0
wcwidth                   0.2.13
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.8.0
Werkzeug                  3.0.3
wheel                     0.43.0
widgetsnbextension        4.0.11
wrapt                     1.16.0
xxhash                    3.4.1
yarl                      1.9.4
zipp                      3.19.1


```

#### 4. Here is ldconfig PATH

```
(20240604) zkpk@master:/usr/sbin$ which ldconfig
/usr/sbin/ldconfig
(20240604) zkpk@master:/usr/sbin$ ldconfig
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
(20240604) zkpk@master:/usr/sbin$ sudo ldconfig
(20240604) zkpk@master:/usr/sbin$ 

```
Is the error due to the Triton 2.1.0 version? I’m confused.

**Comment by zhaomengjiao123** [comment]
> I have already added the path (export PATH=$PATH:/usr/sbin) to ~/.bashrc, but it doesn't work.
> 
> Now I know what the problem is ---- Parcharm did not load the updated system variables, which is too foolish (and so am I)!
> 
> Now the code runs successfully

How did you make it reload? I tried using 'source', but it didn't work for me.

**Comment by Mang30** [comment]
@zhaomengjiao123 Have you solved it？You can restart Pycharm to reload the system path.
