### ISSUE TITLE
Error during backprop when bias=True in Mamba block

### ISSUE THREAD

**Issue by dwromero** [state-spaces/mamba#37]
Hi Albert & Tri,

Awesome work! Thank you for sharing! 

I noticed a bug when using bias=True in a Mamba block. For example, using:

```
layer = Mamba(
        # This module uses roughly 3 * expand * d_model^2 parameters
        d_model=512, # Model dimension d_model
        d_state=16,  # SSM state expansion factor
        d_conv=4,    # Local convolution width
        expand=2,    # Block expansion factor
    ).to("cuda")
```

works perfectly fine, but if I do:

```
layer = Mamba(
        # This module uses roughly 3 * expand * d_model^2 parameters
        d_model=512, # Model dimension d_model
        d_state=16,  # SSM state expansion factor
        d_conv=4,    # Local convolution width
        expand=2,    # Block expansion factor
       bias=True,
    ).to("cuda")
```

I get the error: 

```
Traceback (most recent call last):
  File "/home/dromerog/Projects/meshgen/train.py", line 79, in <module>
    main()
  File "/home/dromerog/Projects/meshgen/train.py", line 71, in main
    trainer.train_loop()
  File "/home/dromerog/Projects/meshgen/meshgen/trainers/autoregressive_mamba.py", line 94, in train_loop
    loss['total'].backward()
  File "/home/dromerog/anaconda3/envs/meshgen/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/dromerog/anaconda3/envs/meshgen/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function MambaInnerFnBackward returned an invalid gradient at index 6 - got [] but expected shape compatible with [512]
```

Hopes this helps! :)

Best,
David

**Comment by Opium1715** [comment]
I also find this problem, hoping resolve it.

**Comment by DeadPackets** [comment]
Bumping this issue, still having this in the latest version.

**Comment by ZeLo-yAnG** [comment]
我找到问题的原因了，在mamba_ssm/ops/selective_scan_interface.py lin 278 and line 287
`class MambaInnerFn(torch.autograd.Function): def backward(ctx, dout):`
你只需要把`dB_proj_bias = dB.sum(0) if not ctx.B_proj_bias_is_None else None `里面的sum(0)去掉就可以了
也就是
`dB_proj_bias = dB if not ctx.B_proj_bias_is_None else None`
对于dC_proj_bias也是一样的做法

I have found the cause of the problem. In mamba_ssm/ops/selective_scan_interface.py at lines 278 and 287, within the class MambaInnerFn(torch.autograd.Function): definition, specifically in the def backward(ctx, dout): method, you just need to remove the .sum(0) from the line:
`dB_proj_bias = dB.sum(0) if not ctx.B_proj_bias_is_None else None`
That is to say:
`dB_proj_bias = dB if not ctx.B_proj_bias_is_None else None`
The same approach should be applied to dC_proj_bias.

**Comment by yashrb24** [comment]
Same needs to be done for
```python
dout_proj_bias = dout.sum(dim=(0, 1)) if not ctx.out_proj_bias_is_None else None
```
It should instead be 
```python
dout_proj_bias = dout.sum(dim=(1)) if not ctx.out_proj_bias_is_None else None
```
(because the shape is e, (b l) and sum is needed across (b l))
