### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by thistleknot** [state-spaces/mamba#39]
oracle linux 8.5
built from source
as well as installed from package
python 3.10
cuda 12.2
pytorch 2.01 for cuda 12.1

)
Building wheels for collected packages: mamba-ssm
  Building wheel for mamba-ssm (setup.py) ... done
  Created wheel for mamba-ssm: filename=mamba_ssm-1.0.1-cp310-cp310-linux_x86_64.whl size=137567739 sha256=1775b610f76d6bc71ffaa72375df8c0afde52c1c14f1c788ad6afee4290adff2
  Stored in directory: /tmp/pip-ephem-wheel-cache-bdzo446u/wheels/e4/00/6b/3fc67b42d0194f9c0988cf52351ff031c56e3607a95badb51c
Successfully built mamba-ssm
WARNING: Ignoring invalid distribution -lash-attn (/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages)
Installing collected packages: argparse, mamba-ssm
  Attempting uninstall: mamba-ssm
    Found existing installation: mamba-ssm 1.0.1
    Uninstalling mamba-ssm-1.0.1:
      Successfully uninstalled mamba-ssm-1.0.1
Successfully installed argparse-1.4.0 mamba-ssm-1.0.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(textgen) [root@pve-m7330 mamba]# python3 simplermambassm.py
python3: can't open file '/home/user/mamba/mamba/simplermambassm.py': [Errno 2] No such file or directory
(textgen) [root@pve-m7330 mamba]# cd ..
(textgen) [root@pve-m7330 mamba]# python3 simplermambassm.py
Traceback (most recent call last):
  File "/home/user/mamba/simplermambassm.py", line 21, in <module>
    from mamba_ssm import Mamba
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/mamba_ssm/__init__.py", line 5, in <module>
    from mamba_ssm.models.mixer_seq_simple import MambaLMHeadModel
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/mamba_ssm/models/mixer_seq_simple.py", line 12, in <module>
    from mamba_ssm.utils.generation import GenerationMixin
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/mamba_ssm/utils/generation.py", line 14, in <module>
    from transformers.generation import GreedySearchDecoderOnlyOutput, SampleDecoderOnlyOutput
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/utils/__init__.py", line 31, in <module>
    from .generic import (
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/utils/generic.py", line 29, in <module>
    from .import_utils import is_flax_available, is_tf_available, is_torch_available, is_torch_fx_proxy
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 74, in <module>
    _flash_attn_2_available = _is_package_available("flash_attn") and version.parse(
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/packaging/version.py", line 54, in parse
    return Version(version)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/packaging/version.py", line 198, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
(textgen) [root@pve-m7330 mamba]#

**Comment by thistleknot** [comment]
this is actually a transformers bug (4.35+)
pip install transformers==4.34.1 solves my issue
