### ISSUE TITLE
RuntimeError: Triton Error [CUDA]: context is destroyed

### ISSUE THREAD

**Issue by yingzhige00** [state-spaces/mamba#390]
This is my program error:
`Mamba 1 took 0.7026619808748364 seconds
Traceback (most recent call last):
  File "/root/mamba_test.py", line 34, in <module>
    mamba2_time = timeit.timeit('try_mamba2(batch, length, dim, x)', number=10, globals=globals())
  File "/opt/conda/envs/mamba2/lib/python3.10/timeit.py", line 234, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "/opt/conda/envs/mamba2/lib/python3.10/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/root/mamba_test.py", line 28, in try_mamba2
    y = model(x)
  File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/mamba_ssm/modules/mamba2.py", line 176, in forward
    out = mamba_split_conv1d_scan_combined(
  File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 912, in mamba_split_conv1d_scan_combined
    return MambaSplitConv1dScanCombinedFn.apply(zxbcdt, conv1d_weight, conv1d_bias, dt_bias, A, D, chunk_size, initial_states, seq_idx, dt_limit, return_final_states, activation, rmsnorm_weight, rmsnorm_eps, outproj_weight, outproj_bias, headdim, ngroups, norm_before_gate)
  File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 113, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 777, in forward
    out_x, _, dt_out, dA_cumsum, states, final_states = _mamba_chunk_scan_combined_fwd(x, dt, A, B, C, chunk_size=chunk_size, D=D, z=None, dt_bias=dt_bias, initial_states=initial_states, seq_idx=seq_idx, dt_softplus=True, dt_limit=dt_limit)
  File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 323, in _mamba_chunk_scan_combined_fwd
    out, out_x = _chunk_scan_fwd(CB, x, dt, dA_cumsum, C, states, D=D, z=z, seq_idx=seq_idx)
  File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_chunk_scan.py", line 1253, in _chunk_scan_fwd
    _chunk_scan_fwd_kernel[grid](
  File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 100, in run
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 100, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 83, in _bench
    return do_bench(kernel_call, warmup=self.warmup, rep=self.rep, quantiles=(0.5, 0.2, 0.8))
  File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/triton/testing.py", line 104, in do_bench
    fn()
  File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 81, in kernel_call
    self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages, **current)
  File "<string>", line 65, in _chunk_scan_fwd_kernel
  File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/triton/compiler/compiler.py", line 579, in __getattribute__
    self._init_handles()
  File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/triton/compiler/compiler.py", line 570, in _init_handles
    mod, func, n_regs, n_spills = fn_load_binary(self.metadata["name"], self.asm[bin_path], self.shared, device)
RuntimeError: Triton Error [CUDA]: context is destroyed
`
This is my code:
`import torch
import timeit
from mamba_ssm import Mamba, Mamba2

batch, length, dim = 2, 64, 256
cuda = "cuda:4"
x = torch.randn(batch, length, dim).to(cuda)

def try_mamba1(batch, length, dim, x):
    model = Mamba(
        # This module uses roughly 3 * expand * d_model^2 parameters
        d_model=dim, # Model dimension d_model
        d_state=16,  # SSM state expansion factor
        d_conv=4,    # Local convolution width
        expand=2,    # Block expansion factor
    ).to(cuda)
    y = model(x)
    assert y.shape == x.shape

def try_mamba2(batch, length, dim, x):
    model = Mamba2(
        # This module uses roughly 3 * expand * d_model^2 parameters
        d_model=dim, # Model dimension d_model
        d_state=64,  # SSM state expansion factor, typically 64 or 128
        d_conv=4,    # Local convolution width
        expand=2,    # Block expansion factor
    ).to(cuda)
    y = model(x)
    assert y.shape == x.shape

mamba1_time = timeit.timeit('try_mamba1(batch, length, dim, x)', number=10, globals=globals())
print(f"Mamba 1 took {mamba1_time} seconds")

mamba2_time = timeit.timeit('try_mamba2(batch, length, dim, x)', number=10, globals=globals())
print(f"Mamba 2 took {mamba2_time} seconds")`
How to solve this error

**Comment by yingzhige00** [comment]
Why can it run after I changed this? But it's too slow.
before:
`batch, length, dim = 2, 64, 256`
after:
`batch, length, dim = 1, 4, 256`

**Comment by tridao** [comment]
Seems like a Triton error. You might have better luck searching their repo issues.

**Comment by JHChen1** [comment]
Hi, I have the same problem, have you solved it?

**Comment by yingzhige00** [comment]
> Hi, I have the same problem, have you solved it?
No
but, I am try...
https://github.com/triton-lang/triton/issues/2861
in this issues, he change "cuda:1" to "cuda:0" or "cuda" is OK.

**Comment by yingzhige00** [comment]
> > Hi, I have the same problem, have you solved it?
> 
> No but, I am try... [triton-lang/triton#2861](https://github.com/triton-lang/triton/issues/2861) in this issues, he change "cuda:1" to "cuda:0" or "cuda" is OK.

This code runs, but it runs slower
```
import torch
import timeit
import os
from mamba_ssm import Mamba, Mamba2


batch, length, dim = 1, 64, 256
os.environ["CUDA_VISIBLE_DEVICES"] = "4"
cuda = "cuda"
x = torch.randn(batch, length, dim).to(cuda)

def try_mamba1(batch, length, dim, x):
    model = Mamba(
        # This module uses roughly 3 * expand * d_model^2 parameters
        d_model=dim, # Model dimension d_model
        d_state=16,  # SSM state expansion factor
        d_conv=4,    # Local convolution width
        expand=2,    # Block expansion factor
    ).to(cuda)
    y = model(x)
    assert y.shape == x.shape

def try_mamba2(batch, length, dim, x):
    model = Mamba2(
        # This module uses roughly 3 * expand * d_model^2 parameters
        d_model=dim, # Model dimension d_model
        d_state=64,  # SSM state expansion factor, typically 64 or 128
        d_conv=4,    # Local convolution width
        expand=2,    # Block expansion factor
    ).to(cuda)
    y = model(x)
    assert y.shape == x.shape

mamba1_time = timeit.timeit('try_mamba1(batch, length, dim, x)', number=10, globals=globals())
print(f"Mamba 1 took {mamba1_time} seconds")

mamba2_time = timeit.timeit('try_mamba2(batch, length, dim, x)', number=10, globals=globals())
print(f"Mamba 2 took {mamba2_time} seconds")
```

**Comment by JHChen1** [comment]
> Seems like a Triton error. You might have better luck searching their repo issues.

Hello, when using other devices instead of cuda:0, "RuntimeError: Triton Error [CUDA]: context is destroyed" will appear. Is there any solution?

**Comment by JHChen1** [comment]
> > > Hi, I have the same problem, have you solved it?
> > 
> > 
> > No but, I am try... [triton-lang/triton#2861](https://github.com/triton-lang/triton/issues/2861) in this issues, he change "cuda:1" to "cuda:0" or "cuda" is OK.
> 
> This code runs, but it runs slower
> 
> ```
> import torch
> import timeit
> import os
> from mamba_ssm import Mamba, Mamba2
> 
> 
> batch, length, dim = 1, 64, 256
> os.environ["CUDA_VISIBLE_DEVICES"] = "4"
> cuda = "cuda"
> x = torch.randn(batch, length, dim).to(cuda)
> 
> def try_mamba1(batch, length, dim, x):
>     model = Mamba(
>         # This module uses roughly 3 * expand * d_model^2 parameters
>         d_model=dim, # Model dimension d_model
>         d_state=16,  # SSM state expansion factor
>         d_conv=4,    # Local convolution width
>         expand=2,    # Block expansion factor
>     ).to(cuda)
>     y = model(x)
>     assert y.shape == x.shape
> 
> def try_mamba2(batch, length, dim, x):
>     model = Mamba2(
>         # This module uses roughly 3 * expand * d_model^2 parameters
>         d_model=dim, # Model dimension d_model
>         d_state=64,  # SSM state expansion factor, typically 64 or 128
>         d_conv=4,    # Local convolution width
>         expand=2,    # Block expansion factor
>     ).to(cuda)
>     y = model(x)
>     assert y.shape == x.shape
> 
> mamba1_time = timeit.timeit('try_mamba1(batch, length, dim, x)', number=10, globals=globals())
> print(f"Mamba 1 took {mamba1_time} seconds")
> 
> mamba2_time = timeit.timeit('try_mamba2(batch, length, dim, x)', number=10, globals=globals())
> print(f"Mamba 2 took {mamba2_time} seconds")
> ```

Thanks for your reply. When I set it the same as you did, it would use cuda:0 by default instead of cuda:1 as I wanted. The program itself can be executed in cuda:0, but the same error as yours will appear in cuda:1. I have not found the reason yet.
"torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 98.00 MiB (GPU 0; 15.77 GiB total capacity; 3.16 GiB already allocated; 86.19 MiB free; 3.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"

**Comment by ZLKong** [comment]
> > Seems like a Triton error. You might have better luck searching their repo issues.
> 
> Hello, when using other devices instead of cuda:0, "RuntimeError: Triton Error [CUDA]: context is destroyed" will appear. Is there any solution?

Hello, I found a solution here https://github.com/facebookresearch/xformers/issues/681

Therefore, in the error log, for the code in 
  File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 323, in _mamba_chunk_scan_combined_fwd
`    out, out_x = _chunk_scan_fwd(CB, x, dt, dA_cumsum, C, states, D=D, z=z, seq_idx=seq_idx)`

I added

```
with torch.cuda.device(CB.device):
        out, out_x = _chunk_scan_fwd(CB, x, dt, dA_cumsum, C, states, D=D, z=z, seq_idx=seq_idx)
```

**Comment by yingzhige00** [comment]
> > > > 你好，我遇到了同样的问题，你解决了吗？
> > > 
> > > 
> > > 不，但是，我尝试... [triton-lang/triton#2861](https://github.com/triton-lang/triton/issues/2861)在这个问题中，他将“cuda：1”更改为“cuda：0”或“cuda”是可以的。
> > 
> > 
> > 这段代码可以运行，但运行速度较慢
> > ```
> > import torch
> > import timeit
> > import os
> > from mamba_ssm import Mamba, Mamba2
> > 
> > 
> > batch, length, dim = 1, 64, 256
> > os.environ["CUDA_VISIBLE_DEVICES"] = "4"
> > cuda = "cuda"
> > x = torch.randn(batch, length, dim).to(cuda)
> > 
> > def try_mamba1(batch, length, dim, x):
> >     model = Mamba(
> >         # This module uses roughly 3 * expand * d_model^2 parameters
> >         d_model=dim, # Model dimension d_model
> >         d_state=16,  # SSM state expansion factor
> >         d_conv=4,    # Local convolution width
> >         expand=2,    # Block expansion factor
> >     ).to(cuda)
> >     y = model(x)
> >     assert y.shape == x.shape
> > 
> > def try_mamba2(batch, length, dim, x):
> >     model = Mamba2(
> >         # This module uses roughly 3 * expand * d_model^2 parameters
> >         d_model=dim, # Model dimension d_model
> >         d_state=64,  # SSM state expansion factor, typically 64 or 128
> >         d_conv=4,    # Local convolution width
> >         expand=2,    # Block expansion factor
> >     ).to(cuda)
> >     y = model(x)
> >     assert y.shape == x.shape
> > 
> > mamba1_time = timeit.timeit('try_mamba1(batch, length, dim, x)', number=10, globals=globals())
> > print(f"Mamba 1 took {mamba1_time} seconds")
> > 
> > mamba2_time = timeit.timeit('try_mamba2(batch, length, dim, x)', number=10, globals=globals())
> > print(f"Mamba 2 took {mamba2_time} seconds")
> > ```
> 
> 感谢您的回复。当我像您一样设置它时，它会默认使用 cuda:0，而不是我想要的 cuda:1。程序本身可以在 cuda:0 中执行，但与您的错误相同的错误会出现在 cuda:1 中。我还没有找到原因。 “torch.cuda.OutOfMemoryError：CUDA 内存不足。尝试分配 98.00 MiB（GPU 0；总容量 15.77 GiB；已分配 3.16 GiB；86.19 MiB 可用；PyTorch 总共保留 3.26 GiB）如果保留内存 >> 分配内存，请尝试设置 max_split_size_mb 以避免碎片。请参阅内存管理和 PYTORCH_CUDA_ALLOC_CONF 的文档”

I think this code will change CUDA to the specified number
`os.environ["CUDA_VISIBLE_DEVICES"] = "4"`
At this point, the cuda:0 used is cuda:4

**Comment by yingzhige00** [comment]
> > > Seems like a Triton error. You might have better luck searching their repo issues.
> > 
> > 
> > Hello, when using other devices instead of cuda:0, "RuntimeError: Triton Error [CUDA]: context is destroyed" will appear. Is there any solution?
> 
> Hello, I found a solution here [facebookresearch/xformers#681](https://github.com/facebookresearch/xformers/issues/681)
> 
> Therefore, in the error log, for the code in File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 323, in _mamba_chunk_scan_combined_fwd ` out, out_x = _chunk_scan_fwd(CB, x, dt, dA_cumsum, C, states, D=D, z=z, seq_idx=seq_idx)`
> 
> I added
> 
> ```
> with torch.cuda.device(CB.device):
>         out, out_x = _chunk_scan_fwd(CB, x, dt, dA_cumsum, C, states, D=D, z=z, seq_idx=seq_idx)
> ```

I try it. result is:
```Mamba 1 took 4.738497721031308 seconds
Mamba 2 took 6.514716611243784 seconds```
but if use my method, the result is:
```
Mamba 1 took 0.6497394228354096 seconds
Mamba 2 took 3.360878186300397 seconds
```
