### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by mahao18cm** [state-spaces/mamba#396]
Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      ninja: error: '/tmp/pip-install-_9k5lp7_/mamba-ssm_f9a8d8dd3bdf4f29b75d4c24172e5e5b/csrc/selective_scan/selective_scan.cpp', needed by '/tmp/pip-install-_9k5lp7_/mamba-ssm_f9a8d8dd3bdf4f29b75d4c24172e5e5b/build/temp.linux-x86_64-cpython-37/csrc/selective_scan/selective_scan.o', missing and no known rule to make it
Traceback (most recent call last):
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
          env=env)
        File "/root/miniconda3/envs/flowformer/lib/python3.7/subprocess.py", line 512, in run
          output=stdout, stderr=stderr)
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_9k5lp7_/mamba-ssm_f9a8d8dd3bdf4f29b75d4c24172e5e5b/setup.py", line 281, in <module>
          "transformers",
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
          build_ext.build_extensions(self)
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
          self._build_extensions_serial()
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
          self.build_extension(ext)
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 556, in build_extension
          depends=ext.depends,
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
          with_cuda=with_cuda)
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
          error_prefix='Error compiling objects for extension')
        File "/root/miniconda3/envs/flowformer/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
          raise RuntimeError(message)
      RuntimeError: Error compiling objects for extension

**Comment by mahao18cm** [comment]
![image](https://github.com/state-spaces/mamba/assets/43996915/2ee33532-2b37-4f7c-90c3-aa3e089b854c)

**Comment by jiaoaoshirenjinbu** [comment]
I have the same problem, please hlep :(

**Comment by jiaoaoshirenjinbu** [comment]
https://github.com/state-spaces/mamba/issues/55#issuecomment-2102446598
my problem solved in this way.

**Comment by mahao18cm** [comment]
> [#55 (comment)](https://github.com/state-spaces/mamba/issues/55#issuecomment-2102446598) my problem solved in this way.
You mean that we just use this command CAUSAL_CONV1D_FORCE_BUILD=TRUE CAUSAL_CONV1D_SKIP_CUDA_BUILD=TRUE CAUSAL_CONV1D_FORCE_CXX11_ABI=TRUE pip install .

**Comment by ARman-AT** [comment]
Anyone find any solution?

**Comment by yangshengaa** [comment]
The above comment https://github.com/state-spaces/mamba/issues/396#issuecomment-2177410850 skips CUDA builds. The resulting causal_conv1d package would not have `causal_conv1d_cuda `needed to run on CUDA device.

Try building from source. That is, clone to local and `pip install .`
