### ISSUE TITLE
mamba2 error

### ISSUE THREAD

**Issue by Zhou-CyberSecurity-AI** [state-spaces/mamba#428]
/tmp/tmpgea0duot/main.c: In function ‘list_to_cuuint64_array’:
/tmp/tmpgea0duot/main.c:354:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (Py_ssize_t i = 0; i < len; i++) {
   ^
/tmp/tmpgea0duot/main.c:354:3: note: use option -std=c99 or -std=gnu99 to compile your code
/tmp/tmpgea0duot/main.c: In function ‘list_to_cuuint32_array’:
/tmp/tmpgea0duot/main.c:365:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (Py_ssize_t i = 0; i < len; i++) {
   ^
Traceback (most recent call last):
  File "/home/cpz/BlackMamba/main.py", line 17, in <module>
    y = model(x)
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/mamba_ssm/modules/mamba2.py", line 177, in forward
    out = mamba_split_conv1d_scan_combined(
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 912, in mamba_split_conv1d_scan_combined
    return MambaSplitConv1dScanCombinedFn.apply(zxbcdt, conv1d_weight, conv1d_bias, dt_bias, A, D, chunk_size, initial_states, seq_idx, dt_limit, return_final_states, activation, rmsnorm_weight, rmsnorm_eps, outproj_weight, outproj_bias, headdim, ngroups, norm_before_gate)
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 115, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 777, in forward
    out_x, _, dt_out, dA_cumsum, states, final_states = _mamba_chunk_scan_combined_fwd(x, dt, A, B, C, chunk_size=chunk_size, D=D, z=None, dt_bias=dt_bias, initial_states=initial_states, seq_idx=seq_idx, dt_softplus=True, dt_limit=dt_limit)
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 311, in _mamba_chunk_scan_combined_fwd
    dA_cumsum, dt = _chunk_cumsum_fwd(dt, A, chunk_size, dt_bias=dt_bias, dt_softplus=dt_softplus, dt_limit=dt_limit)
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_chunk_state.py", line 584, in _chunk_cumsum_fwd
    _chunk_cumsum_fwd_kernel[grid_chunk_cs](
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 143, in run
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 143, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 122, in _bench
    return do_bench(kernel_call, warmup=self.warmup, rep=self.rep, quantiles=(0.5, 0.2, 0.8))
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/triton/testing.py", line 102, in do_bench
    fn()
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 110, in kernel_call
    self.fn.run(
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/triton/runtime/jit.py", line 550, in run
    bin.c_wrapper(
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/triton/compiler/compiler.py", line 692, in __getattribute__
    self._init_handles()
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/triton/compiler/compiler.py", line 670, in _init_handles
    bin_path = {driver.HIP: "hsaco_path", driver.CUDA: "cubin"}[driver.backend]
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/triton/runtime/driver.py", line 157, in __getattr__
    self._initialize_obj()
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/triton/runtime/driver.py", line 154, in _initialize_obj
    self._obj = self._init_fn()
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/triton/runtime/driver.py", line 187, in initialize_driver
    return CudaDriver()
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/triton/runtime/driver.py", line 77, in __init__
    self.utils = CudaUtils()
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/triton/runtime/driver.py", line 47, in __init__
    so = _build("cuda_utils", src_path, tmpdir)
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/triton/common/build.py", line 106, in _build
    ret = subprocess.check_call(cc_cmd)
  File "/home/cpz/anaconda3/envs/mamba/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmpgea0duot/main.c', '-O3', '-I/home/cpz/anaconda3/envs/mamba/lib/python3.10/site-packages/triton/common/../third_party/cuda/include', '-I/home/cpz/anaconda3/envs/mamba/include/python3.10', '-I/tmp/tmpgea0duot', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmpgea0duot/cuda_utils.cpython-310-x86_64-linux-gnu.so', '-L/lib64', '-L/lib', '-L/lib64', '-L/lib']' returned non-zero exit status 1.

**Comment by tridao** [comment]
Looks like a Triton error

**Comment by two-tiger** [comment]
I have the same error. Have you resolved it? My package and CUDA version are as follows:
mamba-ssm 2.2.2
causal-conv1d 1.4.0
torch 2.0.0
cuda 11.8
python 3.10
