### ISSUE TITLE
Mamba-2 Error: `'NoneType' object has no attribute 'causal_conv1d_fwd'`

### ISSUE THREAD

**Issue by hawkheimmer** [state-spaces/mamba#467]
When I'm running
```python
import torch
from mamba_ssm import Mamba, Mamba2

batch, length, dim = 2, 64, 512

x1 = torch.randn(batch, length, dim).to("cuda")
model = Mamba(
    # This module uses roughly 3 * expand * d_model^2 parameters
    d_model=dim, # Model dimension d_model
    d_state=16,  # SSM state expansion factor
    d_conv=4,    # Local convolution width
    expand=2,    # Block expansion factor
).to("cuda")
y1 = model(x1)

x2 = torch.randn(batch, length, dim).to("cuda")
model = Mamba2(
    # This module uses roughly 3 * expand * d_model^2 parameters
    d_model=dim, # Model dimension d_model
    d_state=16,  # SSM state expansion factor
    d_conv=4,    # Local convolution width
    expand=2,    # Block expansion factor
).to("cuda")
y2 = model(x2)
```
the mamba-1 model works fine, but the mamba-2 model encounters the following error:
```python-traceback
Traceback (most recent call last):
  File "/snap/dataspell/92/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 9, in <module>
  File "/home/admin/.conda/envs/myenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/.conda/envs/myenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/.conda/envs/myenv/lib/python3.11/site-packages/mamba_ssm/modules/mamba2.py", line 183, in forward
    out = mamba_split_conv1d_scan_combined(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/.conda/envs/myenv/lib/python3.11/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 930, in mamba_split_conv1d_scan_combined
    return MambaSplitConv1dScanCombinedFn.apply(zxbcdt, conv1d_weight, conv1d_bias, dt_bias, A, D, chunk_size, initial_states, seq_idx, dt_limit, return_final_states, activation, rmsnorm_weight, rmsnorm_eps, outproj_weight, outproj_bias, headdim, ngroups, norm_before_gate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/.conda/envs/myenv/lib/python3.11/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/.conda/envs/myenv/lib/python3.11/site-packages/torch/cuda/amp/autocast_mode.py", line 115, in decorate_fwd
    return fwd(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/.conda/envs/myenv/lib/python3.11/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 779, in forward
    causal_conv1d_cuda.causal_conv1d_fwd(rearrange(xBC, "b s d -> b d s"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'causal_conv1d_fwd'
```
Following are my packages:
```bash
(myenv) admin@admin-Laptop:~$ conda list
# packages in environment at /home/admin/.conda/envs/myenv:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
blas                      1.0                         mkl  
brotli-python             1.0.9           py311h6a678d5_8  
bzip2                     1.0.8                h5eee18b_6  
ca-certificates           2024.7.2             h06a4308_0  
causal-conv1d             1.4.0                    pypi_0    pypi
certifi                   2024.7.4        py311h06a4308_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
cuda-cudart               12.1.105                      0    nvidia
cuda-cupti                12.1.105                      0    nvidia
cuda-libraries            12.1.0                        0    nvidia
cuda-nvrtc                12.1.105                      0    nvidia
cuda-nvtx                 12.1.105                      0    nvidia
cuda-opencl               12.5.39                       0    nvidia
cuda-runtime              12.1.0                        0    nvidia
cuda-version              12.5                          3    nvidia
einops                    0.8.0                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.13.1          py311h06a4308_0  
freetype                  2.12.1               h4a9f257_0  
fsspec                    2024.6.1                 pypi_0    pypi
gmp                       6.2.1                h295c915_3  
gmpy2                     2.1.2           py311hc9b5ff0_0  
gnutls                    3.6.15               he1e5248_0  
huggingface-hub           0.23.4                   pypi_0    pypi
idna                      3.7             py311h06a4308_0  
intel-openmp              2023.1.0         hdb19cb5_46306  
jinja2                    3.1.4           py311h06a4308_0  
jpeg                      9e                   h5eee18b_1  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libcublas                 12.1.0.26                     0    nvidia
libcufft                  11.0.2.4                      0    nvidia
libcufile                 1.10.1.7                      0    nvidia
libcurand                 10.3.6.82                     0    nvidia
libcusolver               11.4.4.55                     0    nvidia
libcusparse               12.0.2.55                     0    nvidia
libdeflate                1.17                 h5eee18b_1  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h5eee18b_3  
libidn2                   2.3.4                h5eee18b_0  
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
libnpp                    12.0.2.50                     0    nvidia
libnvjitlink              12.1.105                      0    nvidia
libnvjpeg                 12.1.1.14                     0    nvidia
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.1                h6a678d5_0  
libunistring              0.9.10               h27cfd23_0  
libuuid                   1.41.5               h5eee18b_0  
libwebp-base              1.3.2                h5eee18b_0  
llvm-openmp               14.0.6               h9e868ea_0  
lz4-c                     1.9.4                h6a678d5_1  
mamba-ssm                 2.2.2                    pypi_0    pypi
markupsafe                2.1.3           py311h5eee18b_0  
mkl                       2023.1.0         h213fc3f_46344  
mkl-service               2.4.0           py311h5eee18b_1  
mkl_fft                   1.3.8           py311h5eee18b_0  
mkl_random                1.2.4           py311hdb19cb5_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpmath                    1.3.0           py311h06a4308_0  
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  3.3             py311h06a4308_0  
ninja                     1.11.1.1                 pypi_0    pypi
numpy                     1.26.4          py311h08b1b3b_0  
numpy-base                1.26.4          py311hf175353_0  
openh264                  2.1.1                h4ff587b_0  
openjpeg                  2.4.0                h9ca470c_2  
openssl                   3.0.14               h5eee18b_0  
packaging                 24.1                     pypi_0    pypi
pillow                    10.3.0          py311h5eee18b_0  
pip                       24.0            py311h06a4308_0  
pysocks                   1.7.1           py311h06a4308_0  
python                    3.11.9               h955ad1f_0  
pytorch                   2.2.2           py3.11_cuda12.1_cudnn8.9.2_0    pytorch
pytorch-cuda              12.1                 ha16c6d3_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pyyaml                    6.0.1           py311h5eee18b_0  
readline                  8.2                  h5eee18b_0  
regex                     2024.5.15                pypi_0    pypi
requests                  2.32.2          py311h06a4308_0  
safetensors               0.4.3                    pypi_0    pypi
setuptools                69.5.1          py311h06a4308_0  
sqlite                    3.45.3               h5eee18b_0  
sympy                     1.12            py311h06a4308_0  
tbb                       2021.8.0             hdb19cb5_0  
tk                        8.6.14               h39e8969_0  
tokenizers                0.19.1                   pypi_0    pypi
torchaudio                2.2.2               py311_cu121    pytorch
torchtriton               2.2.0                     py311    pytorch
torchvision               0.17.2              py311_cu121    pytorch
tqdm                      4.66.4                   pypi_0    pypi
transformers              4.42.4                   pypi_0    pypi
typing_extensions         4.11.0          py311h06a4308_0  
tzdata                    2024a                h04d1e81_0  
urllib3                   2.2.2           py311h06a4308_0  
wheel                     0.43.0          py311h06a4308_0  
xz                        5.4.6                h5eee18b_1  
yaml                      0.2.5                h7b6447c_0  
zlib                      1.2.13               h5eee18b_1  
zstd                      1.5.5                hc292b87_2  
```

**Comment by wulijie123** [comment]
Hi, have you solved this problem? I have the same problem.

**Comment by bijingshichengzi** [comment]
Have you solved this problem? I also encountered this problem when using mamba2.

**Comment by MstarLioning** [comment]
Hello, when I tried running the above code, I found that both Mamba1 and Mamba2 would report errors with the following prompt. Do you know how to fix this?
`Traceback (most recent call last):
  File "/tmp/pycharm_project_672/try.py", line 13, in <module>
    y = model(x)
  File "/root/miniconda3/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/pycharm_project_672/mamba_ssm/modules/mamba_simple.py", line 146, in forward
    out = mamba_inner_fn(
  File "/tmp/pycharm_project_672/mamba_ssm/ops/selective_scan_interface.py", line 317, in mamba_inner_fn
    return MambaInnerFn.apply(xz, conv1d_weight, conv1d_bias, x_proj_weight, delta_proj_weight,
  File "/root/miniconda3/envs/mamba/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/miniconda3/envs/mamba/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 113, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/tmp/pycharm_project_672/mamba_ssm/ops/selective_scan_interface.py", line 187, in forward
    conv1d_out = causal_conv1d_cuda.causal_conv1d_fwd(
TypeError: causal_conv1d_fwd(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: Optional[torch.Tensor], arg3: Optional[torch.Tensor], arg4: bool) -> torch.Tensor

Invoked with: tensor([[[-0.8354,  0.4993, -0.0917,  ..., -0.4671,  0.0564,  0.3007],
         [ 1.4562, -0.2346, -1.0272,  ...,  0.0948,  0.0215,  0.6929],
         [-0.6083, -0.6649,  0.5215,  ...,  0.9785,  0.1255, -0.1806],
         ...,
         [-0.3605, -0.2417,  0.5737,  ...,  0.5146,  0.2063, -1.0960],
         [ 0.1532,  0.1866, -0.2218,  ..., -0.0309,  0.4365, -0.0218],
         [ 0.5738,  0.5750, -0.3201,  ..., -0.4711, -0.1071,  0.2530]],

        [[ 0.2963, -0.7356, -0.0647,  ..., -0.1814, -0.6706,  0.4538`

**Comment by hawkheimmer** [comment]
> Have you solved this problem? I also encountered this problem when using mamba2.

Nope, I guess it's the problem with the versions of CUDA and `causal_conv1d`, see https://github.com/state-spaces/mamba/issues/169#issue-2122414656

**Comment by hawkheimmer** [comment]
> Hello, when I tried running the above code, I found that both Mamba1 and Mamba2 would report errors with the following prompt. Do you know how to fix this? `Traceback (most recent call last): File "/tmp/pycharm_project_672/try.py", line 13, in y = model(x) File "/root/miniconda3/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/root/miniconda3/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/tmp/pycharm_project_672/mamba_ssm/modules/mamba_simple.py", line 146, in forward out = mamba_inner_fn( File "/tmp/pycharm_project_672/mamba_ssm/ops/selective_scan_interface.py", line 317, in mamba_inner_fn return MambaInnerFn.apply(xz, conv1d_weight, conv1d_bias, x_proj_weight, delta_proj_weight, File "/root/miniconda3/envs/mamba/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply return super().apply(*args, **kwargs) # type: ignore[misc] File "/root/miniconda3/envs/mamba/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 113, in decorate_fwd return fwd(*args, **kwargs) File "/tmp/pycharm_project_672/mamba_ssm/ops/selective_scan_interface.py", line 187, in forward conv1d_out = causal_conv1d_cuda.causal_conv1d_fwd( TypeError: causal_conv1d_fwd(): incompatible function arguments. The following argument types are supported: 1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: Optional[torch.Tensor], arg3: Optional[torch.Tensor], arg4: bool) -> torch.Tensor
> 
> Invoked with: tensor([[[-0.8354, 0.4993, -0.0917, ..., -0.4671, 0.0564, 0.3007], [ 1.4562, -0.2346, -1.0272, ..., 0.0948, 0.0215, 0.6929], [-0.6083, -0.6649, 0.5215, ..., 0.9785, 0.1255, -0.1806], ..., [-0.3605, -0.2417, 0.5737, ..., 0.5146, 0.2063, -1.0960], [ 0.1532, 0.1866, -0.2218, ..., -0.0309, 0.4365, -0.0218], [ 0.5738, 0.5750, -0.3201, ..., -0.4711, -0.1071, 0.2530]],
> 
> ```
>     [[ 0.2963, -0.7356, -0.0647,  ..., -0.1814, -0.6706,  0.4538`
> ```

I don't know :( I guess it's the problem of the shape of your tensor

**Comment by hawkheimmer** [comment]
> Hello, when I tried running the above code, I found that both Mamba1 and Mamba2 would report errors with the following prompt. Do you know how to fix this? `Traceback (most recent call last): File "/tmp/pycharm_project_672/try.py", line 13, in y = model(x) File "/root/miniconda3/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/root/miniconda3/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/tmp/pycharm_project_672/mamba_ssm/modules/mamba_simple.py", line 146, in forward out = mamba_inner_fn( File "/tmp/pycharm_project_672/mamba_ssm/ops/selective_scan_interface.py", line 317, in mamba_inner_fn return MambaInnerFn.apply(xz, conv1d_weight, conv1d_bias, x_proj_weight, delta_proj_weight, File "/root/miniconda3/envs/mamba/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply return super().apply(*args, **kwargs) # type: ignore[misc] File "/root/miniconda3/envs/mamba/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 113, in decorate_fwd return fwd(*args, **kwargs) File "/tmp/pycharm_project_672/mamba_ssm/ops/selective_scan_interface.py", line 187, in forward conv1d_out = causal_conv1d_cuda.causal_conv1d_fwd( TypeError: causal_conv1d_fwd(): incompatible function arguments. The following argument types are supported: 1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: Optional[torch.Tensor], arg3: Optional[torch.Tensor], arg4: bool) -> torch.Tensor
> 
> Invoked with: tensor([[[-0.8354, 0.4993, -0.0917, ..., -0.4671, 0.0564, 0.3007], [ 1.4562, -0.2346, -1.0272, ..., 0.0948, 0.0215, 0.6929], [-0.6083, -0.6649, 0.5215, ..., 0.9785, 0.1255, -0.1806], ..., [-0.3605, -0.2417, 0.5737, ..., 0.5146, 0.2063, -1.0960], [ 0.1532, 0.1866, -0.2218, ..., -0.0309, 0.4365, -0.0218], [ 0.5738, 0.5750, -0.3201, ..., -0.4711, -0.1071, 0.2530]],
> 
> ```
>     [[ 0.2963, -0.7356, -0.0647,  ..., -0.1814, -0.6706,  0.4538`
> ```

I don't know :( I guess it's the problem of the shape of your tensor

**Comment by wulijie123** [comment]
> > 你解决了这个问题吗？我在使用 mamba2 时也遇到了这个问题。
> 
> 不，我想这是 CUDA 版本的问题，请参阅 [#169（评论）](https://github.com/state-spaces/mamba/issues/169#issue-2122414656)`causal_conv1d`

Hello, if I use mamba-ssm2.2.2, what version of torch and cuda should I use? I am currently using torch2.0 and cuda11.8, but I still get the error "AttributeError: 'NoneType' object has no attribute 'causal_conv1d_fwd'".

**Comment by mahao18cm** [comment]
> 0.4993

Do you solve this problem? I encounter this problem too.

**Comment by hawkheimmer** [comment]
> > 0.4993
> 
> Do you solve this problem? I encounter this problem too.

I solved the problem by installing .whl file from release according to my torch and CUDA version

**Comment by mahao18cm** [comment]
> > > 0.4993
> > 
> > 
> > Do you solve this problem? I encounter this problem too.
> 
> I solved the problem by installing .whl file from release according to my torch and CUDA version

Thank you , i just set the other parameter as None. I am not sure that it work. Because i am troubled with triton

**Comment by weitunglin** [comment]
I had the same issue after installing mamba_ssm with `pip install mamba-ssm[causal-conv1d]` command.

And after uninstalling `pip uninstall mamba-sim causal-conv1d` and re-installing causal-conv1d and then mamba-ssm core version `pip install causal-conv1d && pip install mamba-ssm`. Issue solved.

**Comment by ptdang1001** [comment]
> I had the same issue after installing mamba_ssm with `pip install mamba-ssm[causal-conv1d]` command.
> 
> And after uninstalling `pip uninstall mamba-ssm causal-conv1d` and re-installing causal-conv1d and then mamba-ssm core version `pip install causal-conv1d && pip install mamba-ssm`. Issue solved.

Thanks a lot. It works for me!

**Comment by poult-lab** [comment]
> I had the same issue after installing mamba_ssm with `pip install mamba-ssm[causal-conv1d]` command.
> 
> And after uninstalling `pip uninstall mamba-ssm causal-conv1d` and re-installing causal-conv1d and then mamba-ssm core version `pip install causal-conv1d && pip install mamba-ssm`. Issue solved.

My CUDA's version is 11.8, I tried your proposed code `pip install causal-conv1d && pip install mamba-ssm`. but that is not working for me.

**Comment by benjaminbuzek** [comment]
I use CUDA version 12.8 and encounter the same issue.

**Comment by FilippoBotti** [comment]
I fixed with `pip uninstall mamba-ssm causal-conv1d` and suddently `pip install --no-cache-dir mamba-ssm==2.1.0 causal-conv1d==1.2.1`
