### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by MstarLioning** [state-spaces/mamba#490]
Hello everyone, I can successfully run Mamba-1 and Mamba-2 on the server when instantiating the model. The server environment is: 3090 or 2080Ti, Cuda11.8, Driver Version: 550.90.07. However, when I migrate to the local server (using conda pack) with the environment: 6*P100, Cuda11.8, Driver Version: 550.90.07, I encounter this error message. What should I do?

import torch
from mamba_ssm import Mamba

batch, length, dim = 2, 64, 16
x = torch.randn(batch, length, dim).to("cuda:0")
model = Mamba(
    # This module uses roughly 3 * expand * d_model^2 parameters
    d_model=dim,  # Model dimension d_model
    d_state=16,  # SSM state expansion factor
    d_conv=4,  # Local convolution width
    expand=2,  # Block expansion factor
).to("cuda:0")
print(model)
y = model(x)
print("Mamba result", y.shape)
assert y.shape == x.shape

import torch
from mamba_ssm import Mamba2

batch, length, dim = 2, 64, 512
x = torch.randn(batch, length, dim).to("cuda")
model = Mamba2(
    # This module uses roughly 3 * expand * d_model^2 parameters
    # make sure d_model * expand / headdim = multiple of 8
    d_model=dim,  # Model dimension d_model
    d_state=64,  # SSM state expansion factor, typically 64 or 128
    d_conv=4,  # Local convolution width
    expand=2,  # Block expansion factor
    headdim=64,  # default 64
).to("cuda")
print(model)
y = model(x)
print("Mamba2 result", y.shape)
assert y.shape == x.shape

/home/fjt/anaconda3/envs/Each_new/bin/python3 /tmp/pycharm_project_399/try.py 
Mamba(
  (in_proj): Linear(in_features=16, out_features=64, bias=False)
  (conv1d): Conv1d(32, 32, kernel_size=(4,), stride=(1,), padding=(3,), groups=32)
  (act): SiLU()
  (x_proj): Linear(in_features=32, out_features=33, bias=False)
  (dt_proj): Linear(in_features=1, out_features=32, bias=True)
  (out_proj): Linear(in_features=32, out_features=16, bias=False)
)
Traceback (most recent call last):
  File "/tmp/pycharm_project_399/try.py", line 14, in <module>
    y = model(x)
  File "/home/fjt/anaconda3/envs/Each_new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/pycharm_project_399/mamba_ssm/modules/mamba_simple.py", line 146, in forward
    out = mamba_inner_fn(
  File "/tmp/pycharm_project_399/mamba_ssm/ops/selective_scan_interface.py", line 317, in mamba_inner_fn
    return MambaInnerFn.apply(xz, conv1d_weight, conv1d_bias, x_proj_weight, delta_proj_weight,
  File "/home/fjt/anaconda3/envs/Each_new/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/fjt/anaconda3/envs/Each_new/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 98, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/tmp/pycharm_project_399/mamba_ssm/ops/selective_scan_interface.py", line 187, in forward
    conv1d_out = causal_conv1d_cuda.causal_conv1d_fwd(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by soroushoraki** [comment]
@MstarLioning Did you resolve this issue?

**Comment by SaiGP** [comment]
Is there a solution for this? Is the GPU a limitation for running causal conv (like doesn't work with 1080Ti, 2070S)?
