### ISSUE TITLE
RuntimeError: Triton Error [CUDA]: misaligned address

### ISSUE THREAD

**Issue by hanghangChen** [state-spaces/mamba#492]
My environment
Package                  Version      Editable project location
------------------------ ------------ ---------------------------------------------------------
absl-py                  2.1.02
addict                   2.4.0
aiohttp                  3.9.10
aiosignal                1.3.1ost2
alembic                  1.13.0
asttokens                2.4.1
async-timeout            4.0.3
attrs                    23.1.0
Automat                  22.10.0
blinker                  1.7.0
buildtools               1.0.6
causal-conv1d            1.1.0
certifi                  2023.11.17
cffi                     1.16.0
charset-normalizer       3.3.2
click                    8.1.7
cloudpickle              3.0.0
constantly               23.10.4
contourpy                1.2.0
copulas                  0.11.0
cycler                   0.12.1
databricks-cli           0.18.0
datasets                 2.15.0
decorator                5.1.1
dill                     0.3.7
docker                   6.1.3
docopt                   0.6.2
einops                   0.7.0
entrypoints              0.4
exceptiongroup           1.2.2
executing                2.0.1
filelock                 3.13.1
Flask                    3.0.0
fonttools                4.46.0
frozenlist               1.4.0
fsspec                   2023.10.0
furl                     2.1.3
gitdb                    4.0.11
GitPython                3.1.40
greenlet                 3.0.2
grpcio                   1.65.1
gunicorn                 21.2.0
huggingface-hub          0.19.4
hyperlink                21.0.0
idna                     3.6
importlib-metadata       7.0.0
incremental              22.10.0
ipdb                     0.13.13
ipython                  8.26.0
itsdangerous             2.1.2
jedi                     0.19.1
Jinja2                   3.1.2
joblib                   1.3.2
kiwisolver               1.4.5
llvmlite                 0.43.0
Mako                     1.3.0
mamba_ssm                1.1.1        /home/xxx/workspace/python/projects/Vim/mamba-1p1p1
Markdown                 3.5.1
MarkupSafe               2.1.3
matplotlib               3.8.2
matplotlib-inline        0.1.7
mlflow                   2.9.1
mmcv                     1.3.8
mmsegmentation           0.14.1
mpmath                   1.3.0
multidict                6.0.4
multiprocess             0.70.15
networkx                 3.2.1
ninja                    1.11.1.1
numba                    0.60.0
numpy                    1.26.2
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.5.82
nvidia-nvtx-cu12         12.1.105
oauthlib                 3.2.2
opencv-python            4.8.1.78
orderedmultidict         1.0.1
packaging                23.2
pandas                   2.1.3
parso                    0.8.4
pexpect                  4.9.0
Pillow                   10.1.0
pip                      24.0
platformdirs             4.1.0
plotly                   5.22.0
prettytable              3.9.0
prompt_toolkit           3.0.47
protobuf                 4.25.1
ptyprocess               0.7.0
pure_eval                0.2.3
pyarrow                  14.0.1
pyarrow-hotfix           0.6
pycparser                2.22
Pygments                 2.18.0
PyJWT                    2.8.0
pyparsing                3.1.1
python-dateutil          2.8.2
python-hostlist          1.23.0
pytz                     2023.3.post1
PyYAML                   6.0.1
querystring-parser       1.2.4
redo                     2.0.4
regex                    2023.10.3
requests                 2.31.0
safetensors              0.4.1
scikit-base              0.8.1
scikit-learn             1.3.2
scipy                    1.11.4
setuptools               69.5.1
shap                     0.46.0
simplejson               3.19.2
six                      1.16.0
sktime                   0.31.0
slicer                   0.0.8
smmap                    5.0.1
soundfile                0.12.1
SQLAlchemy               2.0.23
sqlparse                 0.4.4
stack-data               0.6.3
sympy                    1.12
tabulate                 0.9.0
tenacity                 8.4.1
tensorboard              2.17.0
tensorboard-data-server  0.7.2
threadpoolctl            3.2.0
timm                     0.4.12
tokenizers               0.15.0
tomli                    2.0.1
torch                    2.1.2+cu118
torchaudio               2.1.2+cu118
torchdata                0.7.0
torchtext                0.16.0
torchvision              0.16.2+cu118
tqdm                     4.66.1
traitlets                5.14.3
transformers             4.35.2
triton                   2.1.0
Twisted                  24.3.0
typing_extensions        4.8.0
tzdata                   2023.3
urllib3                  2.1.0
wcwidth                  0.2.12
websocket-client         1.7.0
Werkzeug                 3.0.1
wfdb                     4.1.2
wheel                    0.43.0
xlrd                     2.0.1
xlutils                  2.0.0
xlwt                     1.3.0
xxhash                   3.4.1
yapf                     0.40.2
yarl                     1.9.4
zipp                     3.17.0
zope.interface           6.4.post2
![屏幕截图 2024-07-25 215839](https://github.com/user-attachments/assets/4f352b7d-c859-405d-8575-abd4ebfa857f)
I got the message
Traceback (most recent call last):
  File "/home/xxx/workspace/python/projects/Vim/mamba-1p1p1/mamba_ssm/ops/triton/ssd_chunk_state.py", line 675, in _chunk_cumsum_fwd
    _chunk_cumsum_fwd_kernel[grid_chunk_cs](
  File "/home/xxx/anaconda3/envs/VimMamba/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 100, in run
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/home/xxx/anaconda3/envs/VimMamba/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 100, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/home/xxx/anaconda3/envs/VimMamba/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 83, in _bench
    return do_bench(kernel_call, warmup=self.warmup, rep=self.rep, quantiles=(0.5, 0.2, 0.8))
  File "/home/xxx/anaconda3/envs/VimMamba/lib/python3.10/site-packages/triton/testing.py", line 104, in do_bench
    fn()
  File "/home/xxx/anaconda3/envs/VimMamba/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 81, in kernel_call
    self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages, **current)
  File "<string>", line 65, in _chunk_cumsum_fwd_kernel
  File "/home/xxx/anaconda3/envs/VimMamba/lib/python3.10/site-packages/triton/compiler/compiler.py", line 579, in __getattribute__
    self._init_handles()
  File "/home/xxx/anaconda3/envs/VimMamba/lib/python3.10/site-packages/triton/compiler/compiler.py", line 570, in _init_handles
    mod, func, n_regs, n_spills = fn_load_binary(self.metadata["name"], self.asm[bin_path], self.shared, device)
RuntimeError: Triton Error [CUDA]: misaligned address

**Comment by weili419** [comment]
Hello, have you solved this problem? Can you share your experience?
