### ISSUE TITLE
How does the code run on the Macbook

### ISSUE THREAD

**Issue by 524125153** [state-spaces/mamba#546]
My current device is only Macbook, its corresponding chip is M1 chip, and there is no cuda, in this case, I can not run this code？

**Comment by Anri-Lombard** [comment]
Exactly right. You need to have Cuda to use mamba; I've had the same experience as you a while back (luckily I use our university HPC cluster, so do have the needed GPU). You could run it on Google Colab or Kaggle if you want, just watch out since you'll have limited GPU time.

**Comment by josmithiii** [comment]
You can run mamba-minimal on a Mac: https://github.com/johnma2006/mamba-minimal.git

**Comment by dataf3l** [comment]
I am trying to run something called zonos and it fails because mamba_ssm doesn't work for m1 osx.

```
➜  Zonos git:(main) uv run python3 sample.py 
Traceback (most recent call last):
  File "/Users/b/study/ml/voice/cloning/zonos/Zonos/sample.py", line 3, in <module>
    from zonos.model import Zonos
  File "/Users/b/study/ml/voice/cloning/zonos/Zonos/zonos/model.py", line 8, in <module>
    from mamba_ssm.utils.generation import InferenceParams
ModuleNotFoundError: No module named 'mamba_ssm'
➜  Zonos git:(main) uv add mamba_ssm        
```

is there a setting for this package to work on CPU only?
