### ISSUE TITLE
Mamba2 Error subprocess.CalledProcessError: Command [] returned non-zero exit status 1.

### ISSUE THREAD

**Issue by two-tiger** [state-spaces/mamba#549]
Traceback (most recent call last):
  File "/mnt/petrelfs/qibiqing/models/Mamba-Llama-3-8B/models/models.py", line 153, in <module>
    student_model_outputs = student_model.generate(
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/transformers/generation/utils.py", line 1989, in generate
    result = self._sample(
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/transformers/generation/utils.py", line 2932, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1145, in forward
    outputs = self.model(
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 946, in forward
    layer_outputs = decoder_layer(
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/petrelfs/qibiqing/models/Mamba-Llama-3-8B/models/models.py", line 31, in forward
    hidden_states = self.mamba(hidden_states)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/mamba_ssm/modules/mamba2.py", line 183, in forward
    out = mamba_split_conv1d_scan_combined(
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 930, in mamba_split_conv1d_scan_combined
    return MambaSplitConv1dScanCombinedFn.apply(zxbcdt, conv1d_weight, conv1d_bias, dt_bias, A, D, chunk_size, initial_states, seq_idx, dt_limit, return_final_states, activation, rmsnorm_weight, rmsnorm_eps, outproj_weight, outproj_bias, headdim, ngroups, norm_before_gate)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 113, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 795, in forward
    out_x, _, dt_out, dA_cumsum, states, final_states = _mamba_chunk_scan_combined_fwd(x, dt, A, B, C, chunk_size=chunk_size, D=D, z=None, dt_bias=dt_bias, initial_states=initial_states, seq_idx=seq_idx, dt_softplus=True, dt_limit=dt_limit)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 312, in _mamba_chunk_scan_combined_fwd
    dA_cumsum, dt = _chunk_cumsum_fwd(dt, A, chunk_size, dt_bias=dt_bias, dt_softplus=dt_softplus, dt_limit=dt_limit)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_chunk_state.py", line 675, in _chunk_cumsum_fwd
    _chunk_cumsum_fwd_kernel[grid_chunk_cs](
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 100, in run
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 100, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 83, in _bench
    return do_bench(kernel_call, warmup=self.warmup, rep=self.rep, quantiles=(0.5, 0.2, 0.8))
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/triton/testing.py", line 104, in do_bench
    fn()
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 81, in kernel_call
    self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages, **current)
  File "<string>", line 63, in _chunk_cumsum_fwd_kernel
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/triton/compiler/compiler.py", line 425, in compile
    so_path = make_stub(name, signature, constants)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/triton/compiler/make_launcher.py", line 39, in make_stub
    so = _build(name, src_path, tmpdir)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/triton/common/build.py", line 90, in _build
    ret = subprocess.check_call(cc_cmd)
  File "/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/mnt/petrelfs/share/gcc/gcc-11.2.0/bin/gcc', '/tmp/tmp07f0lrb6/main.c', '-O3', '-I/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/lib/python3.10/site-packages/triton/common/../third_party/cuda/include', '-I/mnt/petrelfs/qibiqing/anaconda3/envs/llama_mamba/include/python3.10', '-I/tmp/tmp07f0lrb6', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmp07f0lrb6/_chunk_cumsum_fwd_kernel.cpython-310-x86_64-linux-gnu.so', '-L/lib64', '-L/lib', '-L/lib64', '-L/lib']' returned non-zero exit status 1.

My package and CUDA version are as follows:
mamba-ssm 2.2.2
causal-conv1d 1.4.0
torch 2.1.0
cuda 11.8
python 3.10
triton 2.1.0

**Comment by TheTimmy** [comment]
Same error here. Did you find a fix for it?

**Comment by gnillling** [comment]
Have you solved it? @TheTimmy @two-tiger

**Comment by TheTimmy** [comment]
@gnillling unfortunately not. I'm still searching for a solution.

**Comment by MaxMorning** [comment]
我通过下面方法解决了这一问题，希望对你有用：  

如果运行```ldconfig -p | grep libcuda```得到如下输出：  
```
// SOMETHING HERE
libcuda.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcuda.so.1
```
而不是  
```
// SOMETHING HERE
libcuda.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcuda.so.1
libcuda.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libcuda.so
```

那么可能是由于缺少```libcuda.so```，导致```Triton```编译过程中```gcc```无法找到```libcuda```，使得```-lcuda```选项产生报错；  

解决方案：  

1. 在```/lib/x86_64-linux-gnu/```下建立指向```libcuda.so.1```的```libcuda.so```软链接可能有效：
```
sudo ln -s /lib/x86_64-linux-gnu/libcuda.so.1 /lib/x86_64-linux-gnu/libcuda.so
```

2. 如果你和我一样不能 / 不想用```sudo```，可以将```site-packages/triton/runtime/build.py```的相关部分修改为：
```python
    cc_cmd = [cc, src, "-O3", "-shared", "-fPIC", "-Wno-psabi", "-o", so]
    cc_cmd += ['-l:libcuda.so.1']  # NEW CODE HERE
    # cc_cmd += [f'-l{lib}' for lib in libraries]
    cc_cmd += [f"-L{dir}" for dir in library_dirs]
    cc_cmd += [f"-I{dir}" for dir in include_dirs if dir is not None]
```
直接修改```site-packages```中的代码是有风险的，但我通过这一修改解决了问题。

Here is the English version:

I have solved this problem through the following method, hope it will be useful to you:

If running ```ldconfig -p | grep libcuda``` yields the following output:
```
// SOMETHING HERE
libcuda.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcuda.so.1
```
Instead of
```
// SOMETHING HERE
libcuda.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcuda.so.1
libcuda.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libcuda.so
```

Then it is likely that the absence of ```libcuda.so``` is causing ```gcc``` to fail to locate ```libcuda``` during the compilation of ```Triton```, resulting in an error with the ```-lcuda``` option;

Solution:

1. Creating a soft link to ``libcuda.so.1`` named ```libcuda.so``` under ```/lib/x86_64-linux-gnu/``` might work:
```
sudo ln -s /lib/x86_64-linux-gnu/libcuda.so.1 /lib/x86_64-linux-gnu/libcuda.so
```

2. If you are like me and cannot / do not want to use ```sudo```, you can modify the relevant part of ```site-packages/triton/runtime/build.py``` as follows:
```python
    cc_cmd = [cc, src, "-O3", "-shared", "-fPIC", "-Wno-psabi", "-o", so]
    cc_cmd += ['-l:libcuda.so.1']  # NEW CODE HERE
    # cc_cmd += [f'-l{lib}' for lib in libraries]
    cc_cmd += [f"-L{dir}" for dir in library_dirs]
    cc_cmd += [f"-I{dir}" for dir in include_dirs if dir is not None]
```
Modifying the code directly in ```site-packages``` is risky, but I have resolved the issue through this modification.
