### ISSUE TITLE
Error when install from source on windows

### ISSUE THREAD

**Issue by DStarEpoch** [state-spaces/mamba#561]
I try to install by typing 
`pip install .`
from source in windows, and get errors:

> Processing e:\mamba-ssm\mamba
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
> 
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [23 lines of output]
>       C:\Users\Administrator\AppData\Local\Temp\pip-build-env-9652a1ll\overlay\Lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
>         cpu = _conversion_method_template(device=torch.device("cpu"))
>       <string>:118: UserWarning: mamba_ssm was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
> 
> 
>       torch.__version__  = 2.4.1+cpu
> 
> 
>       Traceback (most recent call last):
>         File "D:\software\miniconda3\envs\Mamba-SSM\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
>           main()
>         File "D:\software\miniconda3\envs\Mamba-SSM\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "D:\software\miniconda3\envs\Mamba-SSM\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>         File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-9652a1ll\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=[])
>         File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-9652a1ll\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
>           self.run_setup()
>         File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-9652a1ll\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
>           exec(code, locals())
>         File "<string>", line 188, in <module>
>       NameError: name 'bare_metal_version' is not defined
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

I was confusing that
I already install cuda and nvcc, but it seems not detect torch version and nvcc on Path. Here is information of torch   and nvcc:
`nvcc --version`

> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2024 NVIDIA Corporation
> Built on Wed_Aug_14_10:26:51_Pacific_Daylight_Time_2024
> Cuda compilation tools, release 12.6, V12.6.68
> Build cuda_12.6.r12.6/compiler.34714021_0

`pip show torch`

> Name: torch
> Version: 2.3.1+cu118
> Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
> Home-page: https://pytorch.org/
> Author: PyTorch Team
> Author-email: packages@pytorch.org
> License: BSD-3
> Location: d:\software\miniconda3\envs\mamba-ssm\lib\site-packages
> Requires: filelock, fsspec, jinja2, mkl, networkx, sympy, typing-extensions
> Required-by:

**Comment by TinChung41** [comment]
I also encounter this problem after making sure install 
`mamba install -c nvidia cuda-nvcc`
on my Saturn Cloud image. This is inconsistent though. First time on another image after install the nvcc on the environment it work with the 
```
pip install --no-use-pep517 causal-conv1d>=1.2.0
pip install mamba_ssm
```

pip install --no-use-pep517 causal-conv1d>=1.2.0
```
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      /tmp/pip-install-okauxcxc/causal-conv1d_7721d6a781ed44e89dfcba384dc3416f/setup.py:113: UserWarning: causal_conv1d was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-okauxcxc/causal-conv1d_7721d6a781ed44e89dfcba384dc3416f/setup.py", line 185, in <module>
          if bare_metal_version >= Version("11.8"):
      NameError: name 'bare_metal_version' is not defined
      
      
      torch.__version__  = 2.3.1.post100
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
jovyan@w-tinch-mambatheisfull2-0bcfa22156a94d00a56a836e8f7e831b-76kxst:~/workspace$ nvidia-smi
Sat Oct 12 10:47:57 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.06             Driver Version: 535.183.06   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       On  | 00000000:00:1E.0 Off |                    0 |
| N/A   25C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
jovyan@w-tinch-mambatheisfull2-0bcfa22156a94d00a56a836e8f7e831b-76kxst:~/workspace$ 
```

**Comment by PolarisLight** [comment]
Exactly the same problem.

**Comment by Liampour** [comment]
I am facing the same issue. Any updates?
