### ISSUE TITLE
undefined symbol: _ZN3c107WarningC1ESt7variantIJNS0_11UserWarningENS0_18DeprecationWarningEEERKNS_14SourceLocationESsb

### ISSUE THREAD

**Issue by PessoaP** [state-spaces/mamba#582]
Hi, I have recently installed mamba-ssm and when I try to use it in python I get this error msg. Any idea on what is missing?

>>> from mamba_ssm import Mamba
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda3/envs/mamba/lib/python3.11/site-packages/mamba_ssm/__init__.py", line 3, in <module>
    from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn
  File "/home/user/anaconda3/envs/mamba/lib/python3.11/site-packages/mamba_ssm/ops/selective_scan_interface.py", line 16, in <module>
    import selective_scan_cuda
ImportError: /home/user/anaconda3/envs/mamba/lib/python3.11/site-packages/selective_scan_cuda.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN3c107WarningC1ESt7variantIJNS0_11UserWarningENS0_18DeprecationWarningEEERKNS_14SourceLocationESsb

**Comment by YicongHong** [comment]
I just met this issue today, upgrade my torch with a cuda matches my nvidia-smi cuda works for me.
e.g., nvidia-smi --> CUDA Version: 12.4
So I did `pip install torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 --index-url https://download.pytorch.org/whl/cu124` solve this problem.

**Comment by CacatuaAlan** [comment]
Hi! I fix the same problem by "pip install mamba-ssm-2.0.3"
and my environment as follows:
cuda-11.8/
torch==2.1.1

**Comment by AlwaysFHao** [comment]
This error is caused by the environment used for precompiling the WHL file not matching your local environment. You can install it using local compilation. You can refer to my blog: https://github.com/AlwaysFHao/Mamba-Install .
