### ISSUE TITLE
Failed to build mamba_ssm : Command ['ninja', '-v'] returned non-zero exit status 1

### ISSUE THREAD

**Issue by WANGXiao0622** [state-spaces/mamba#599]
I'm trying to `pip install mamba_ssm` and during compiling I got this ERROR:

> Emitting ninja build file /mnt/d/Transfer_packages/mamba_ssm-2.2.2/build/temp.linux-x86_64-cpython-310/build.ninja...
>       Compiling objects...
>       Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
>       ninja: error: '/mnt/d/Transfer_packages/mamba_ssm-2.2.2/csrc/selective_scan/selective_scan.cpp', needed by '/mnt/d/Transfer_packages/mamba_ssm-2.2.2/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/selective_scan.o', missing and no known rule to make it
>       Traceback (most recent call last):
>         File "/home/wangxiao/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2104, in _run_ninja_build
>           subprocess.run(
>         File "/usr/lib/python3.10/subprocess.py", line 526, in run
>           raise CalledProcessError(retcode, process.args,
>       subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

I'm using NVIDIA 4070 and CUDA 12.4 (below the nvcc -V output)
> user1@WorkStation:/mnt/e/python_test/GPU_TEST$ nvcc -V
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2024 NVIDIA Corporation
> Built on Tue_Feb_27_16:19:38_PST_2024
> Cuda compilation tools, release 12.4, V12.4.99
> Build cuda_12.4.r12.4/compiler.33961263_0 

and **python 3.10.2**,  **torch 2.5.0**
other packages were downloaded automaticaly by `pip download mamba_ssm`

Is this a problem of torch and cuda versions? Cause in the installation requirements only mentioned PyTorch 1.12+ and CUDA 11.6+, but I'm using the latest version of 2.5.0 and 12.4.

I saw someone suggests to change the "ninja -v" to "ninja --version", I think that's not the root cause and doesn't solve the error.

**Comment by WANGXiao0622** [comment]
Solved with torch 2.2 and cuda 11.8
