### ISSUE TITLE
mamba-ssm 2.2.2 fails to install/build  with torch 2.5.0a0 version

### ISSUE THREAD

**Issue by borisfom** [state-spaces/mamba#615]
Here: 
```
#13 752.5   Building wheel for mamba-ssm (setup.py): finished with status 'error'
#13 752.5   error: subprocess-exited-with-error
#13 752.5
#13 752.5   × python setup.py bdist_wheel did not run successfully.
#13 752.5   │ exit code: 1
#13 752.5   ╰─> [148 lines of output]
#13 752.5       No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
#13 752.5
#13 752.5
#13 752.5       torch.__version__  = 2.5.0a0+e000cf0ad9.nv24.10
#13 752.5
#13 752.5
#13 752.5       running bdist_wheel
#13 752.5       Guessing wheel URL:  https://github.com/state-spaces/mamba/releases/download/v2.2.2/mamba_ssm-2.2.2+cu122torch2.5cxx11abiTRUE-cp310-cp310-linux_x86_64.whl
#13 752.5       Precompiled wheel not found. Building from source...
...
#13 752.5       building 'selective_scan_cuda' extension
#13 752.5       creating /tmp/pip-install-j08w79zo/mamba-ssm_a5c2f146741a47119fe8d215c83b3567/build/temp.linux-x86_64-cpython-310
#13 752.5       creating /tmp/pip-install-j08w79zo/mamba-ssm_a5c2f146741a47119fe8d215c83b3567/build/temp.linux-x86_64-cpython-310/csrc
#13 752.5       creating /tmp/pip-install-j08w79zo/mamba-ssm_a5c2f146741a47119fe8d215c83b3567/build/temp.linux-x86_64-cpython-310/csrc/selective_scan
#13 752.5       Emitting ninja build file /tmp/pip-install-j08w79zo/mamba-ssm_a5c2f146741a47119fe8d215c83b3567/build/temp.linux-x86_64-cpython-310/build.ninja...
#13 752.5       Compiling objects...
#13 752.5       Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
#13 752.5       ninja: error: '/tmp/pip-install-j08w79zo/mamba-ssm_a5c2f146741a47119fe8d215c83b3567/csrc/selective_scan/selective_scan.cpp', needed by '/tmp/pip-install-j08w7\
9zo/mamba-ssm_a5c2f146741a47119fe8d215c83b3567/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/selective_scan.o', missing and no known rule to make it
#13 752.5       Traceback (most recent call last):
#13 752.5         File "/tmp/pip-install-j08w79zo/mamba-ssm_a5c2f146741a47119fe8d215c83b3567/setup.py", line 318, in run
#13 752.5           urllib.request.urlretrieve(wheel_url, wheel_filename)
#13 752.5         File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
#13 752.5           with contextlib.closing(urlopen(url, data)) as fp:
#13 752.5         File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
#13 752.5           return opener.open(url, data, timeout)
#13 752.5         File "/usr/lib/python3.10/urllib/request.py", line 525, in open
#13 752.5           response = meth(req, response)
#13 752.5         File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
#13 752.5           response = self.parent.error(
#13 752.5         File "/usr/lib/python3.10/urllib/request.py", line 563, in error
#13 752.5           return self._call_chain(*args)
#13 752.5         File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
#13 752.5           result = func(*args)
#13 752.5         File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
#13 752.5           raise HTTPError(req.full_url, code, msg, hdrs, fp)
#13 752.5       urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by borisfom** [comment]
It works fine when installed from source (trunk) - is I suppose it's time to produce 2.2.3!

**Comment by bhack** [comment]
Same issue

**Comment by werruww** [comment]
!git clone https://github.com/state-spaces/mamba.git

%cd mamba

!pip install -e .


It takes a long time.
colab t4

**Comment by werruww** [comment]
؟؟؟؟؟؟؟؟؟؟؟

**Comment by DavyD1511** [comment]
@borisfom, I have the same issue. How did you manage to make it work ?
