### ISSUE TITLE
Installation error with pip

### ISSUE THREAD

**Issue by ErdiTk** [state-spaces/mamba#639]
I am trying to install it but I get the following error:
```

pip install mamba-ssm --no-build-isolation
Collecting mamba-ssm
  Using cached mamba_ssm-2.2.4.tar.gz (91 kB)
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      <string>:118: UserWarning: mamba_ssm was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
      
      
      torch.__version__  = 2.5.1+cu124
      
      
      Traceback (most recent call last):
        File "path_to_venv/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "path_to_venv/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/path_to_venv/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "path_to_venv/venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "path_to_venv/venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 188, in <module>
      NameError: name 'bare_metal_version' is not defined
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I tried to look on other open issues but none seems to match this. Is there something I am doing wrong?
I have to include the `--no-build-isolation` to avoid the torch is missing error.

**Comment by yunqingliu1996** [comment]
try pip install mamba-ssm[causal-conv1d] --no-build-isolation

**Comment by ErdiTk** [comment]
> try pip install mamba-ssm[causal-conv1d] --no-build-isolation

I tried but still get the same exact error.

**Comment by lifeiteng** [comment]
same error

**Comment by lifeiteng** [comment]
export MAMBA_SKIP_CUDA_BUILD=TRUE

**Comment by yihuai-gao** [comment]
If you are using a conda environment, activate this environment and install cuda to your current environment by running `conda install cuda=12.4`. Then you should be able to build the cuda kernel
